### ISSUE TITLE
Seeing image tinted green when resized. 

### ISSUE THREAD

**Issue by ay8s** [willnorris/imageproxy#102]
When viewing the raw image without the proxy the image is displayed fine, when the image is resized it comes back with a green tint as though something has gone wrong with the image channels. Wonder if you have seen this before and whether there may be something misconfigured on our side that would cause this?

Raw Image: https://cl.ly/0e472t1s2T3v

Proxied: https://cl.ly/1N2925313c2V

**Comment by willnorris** [comment]
Weird.  No, I've certainly never seen anything like this before.  

Here's a quick attempt at uploading your raw image to my server and proxying it, which looks fine:

https://willnorris.com/api/imageproxy/800/https://willnorris.com/tmp/test-image.jpg

**Comment by willnorris** [comment]
I've tried a couple of times and am not able to reproduce this.  Is this still happening for you?  Are you seeing it with just this one image, or others as well?

**Comment by willnorris** [comment]
closing old issue with no response.
