### ISSUE TITLE
WebP output - killer feature 

### ISSUE THREAD

**Issue by slav123** [willnorris/imageproxy#114]
I wrote similar service a while ago. Idea almost exactly as yours - for me killer feature was option to serve webp images as an output. It was based on browser detection (Chrome & Opera). Maybe there is a change at least ad ,webp output in yours ?

**Comment by willnorris** [comment]
See comments in #76 and #88.  The only thing holding me back from adding webp encoding is just a library that supports it.  As far as I know, no such Go library exists.

**Comment by slav123** [comment]
It's just a matter of using vips to handle scaling. Sory for my spaghetti code it was long learning curve for me: 

[https://github.com/slav123/go-resizer](https://github.com/slav123/go-resizer)

but basically this library solves your problem:

https://github.com/h2non/bimg/tree/v1.0.14

**Comment by ramiel** [comment]
What about https://github.com/nickalie/go-webpbin?

**Comment by willnorris** [comment]
> What about nickalie/go-webpbin?

that's simply a wrapper around a command line tool, not an actual go library.

**Comment by ramiel** [comment]
And https://github.com/chai2010/webp instead?
Sorry, I'm not a GO developer

**Comment by willnorris** [comment]
chai2010/webp is using cgo, which makes things more complicated and less portable (read more at https://dave.cheney.net/2016/01/18/cgo-is-not-go).

As people have added more caching storage backends, and the imageproxy binary size has grown pretty substantially, I've been thinking about how to rearchitect it to have some sort of plugin system.  If and when that were to happen, I'd be fine with added an optional plugin that used cgo or called out to separate process.  But as things are now, my plan is to limit it to pure go.

**Comment by ramiel** [comment]
Well, good to discover new things.

**Comment by tuananh** [comment]
@willnorris has anything change regarding ewbp support in go?

**Comment by willnorris** [comment]
Not that I'm aware of

**Comment by muety** [comment]
@slav123 Does the code of your service still exist somewhere? I'm basically looking for exactly what you seem to have build – an image proxy that conditionally converts PNG or JPG to webp if the requesting browser supports it.

**Comment by ramiel** [comment]
https://caravaggio.ramielcreations.com/

**Comment by slav123** [comment]
Hi,

Look for project called "imaginary" - it's pretty much what I was building on my own. 

I will share my project on Monday maybe (I'm on holidays right now)

pozdrawiam Sławomir Jasiński

**Comment by willnorris** [comment]
There's also github.com/imgproxy/imgproxy if you want to stick with something written in (mostly) go.  They use cgo, which allows them to add webp support, use vips for faster transformations and encoding, etc.

**Comment by zquestz** [comment]
I forked this project to add webp encoding. Hopefully it is useful to some folks. I have it in production and it is quite stable.

https://github.com/zquestz/imageproxy

**Comment by tuananh** [comment]
> I forked this project to add webp encoding. Hopefully it is useful to some folks. I have it in production and it is quite stable.
> 
> https://github.com/zquestz/imageproxy

This is very nice. Why not put a pr here?

**Comment by willnorris** [comment]
> This is very nice. Why not put a pr here?

Because I wouldn't merge it :)  As discussed in this and related issues, I've decided to keep imageproxy as only using pure go libraries, not any that require cgo.  https://github.com/kolesa-team/go-webp, which @zquestz's fork uses, requires cgo.

**Comment by tuananh** [comment]
I see. Maybe document this fork in the readme for better visibility?

**Comment by willnorris** [comment]
filed #353 to track that

**Comment by sunstarjeff** [comment]
> I forked this project to add webp encoding. Hopefully it is useful to some folks. I have it in production and it is quite stable.
> 
> https://github.com/zquestz/imageproxy

Pardon my ignorance, but how would someone who already uses ImageProxy install and utilize your fork in order to realize .webp in/out?

**Comment by zquestz** [comment]
> > I forked this project to add webp encoding. Hopefully it is useful to some folks. I have it in production and it is quite stable.
> > https://github.com/zquestz/imageproxy
> 
> Pardon my ignorance, but how would someone who already uses ImageProxy install and utilize your fork in order to realize .webp in/out?

Easiest way is with docker. `docker run -p 8080:8080 zquestz/imageproxy -addr 0.0.0.0:8080`

Then in your resizer call, add webp as the output. For instance `https://resizer.example.com/750x,webp/https://somehost.com/image.png`

**Comment by sunstarjeff** [comment]
Thank you, we're running an existing command line process in a production environment which runs a batch file with "imageproxy -allowHosts *host.com".  Since your fork has the same name, I'm just not very clear on how it would work to attempt to run an alternate library.  Likely, it's my own ignorance on the subject.  I wish the primary ImageProxy library had webp support, with Google PageSpeed now giving sites a negative score for sites that don't offer "next gen formats".

**Comment by zquestz** [comment]
Ahh to build it. Just do the following:

1. Clone github.com/zquestz/imageproxy
2. `cd imageproxy/cmd/imageproxy`
3. `go install .`

This should build a working binary with the updated feature set.
