### ISSUE TITLE
URL signing & URL encoded characters

### ISSUE THREAD

**Issue by branimir93** [willnorris/imageproxy#115]
We have a problem with signing requests that have URL encoded characters e.g. comma.

For example, the original URL string on which I have calculated the signature is:
```
https://3.bp.blogspot.com/-U5eFGLc-DF8/WdJ6XXrTj-I/AAAAAAAAqKE/Kk5LN3ev5soLDlQ0Gpts_AllY5Q-Pu7kwCLcBGAs/s1600/Plitvice+National+Park%2C+Croatia+-+Posh%2C+Broke%2C+%26+Bored_1.JPG
```
But when image proxy is checking that signature, it will calculate it upon normalised URL:
```
https://3.bp.blogspot.com/-U5eFGLc-DF8/WdJ6XXrTj-I/AAAAAAAAqKE/Kk5LN3ev5soLDlQ0Gpts_AllY5Q-Pu7kwCLcBGAs/s1600/Plitvice+National+Park,+Croatia+-+Posh,+Broke,+&+Bored_1.JPG
```

I think that the right way for solving this would be that imageproxy is calculating the signature upon original request, `req.URL.RawPath`

The only thing that needs to be changed is: 
[data.go#L336](https://github.com/willnorris/imageproxy/blob/7dbadc01d49ee17747bffbd0ccb33cd6a4f07975/data.go#L336)
```
	path := r.URL.Path[1:] // strip leading slash
````
```
	path := r.URL.RawPath[1:] // strip leading slash
```

**Comment by willnorris** [comment]
`RawPath` isn't always populated, so `EscapedPath()` is actually what is needed here.  Fixed, and thanks for the bug report!
