### ISSUE TITLE
add support for jpeg quality option

### ISSUE THREAD

**Issue by willnorris** [willnorris/imageproxy#12]
adding this as a placeholder for @cubabit's work in his [add-quality-option branch](https://github.com/cubabit/imageproxy/compare/add-quality-option) (at least, I assume you intended to contribute this.  Note also the relevant changes I made in 0980ea64a012b31c12f89ab1c226fc805bbabf70)

**Comment by cubabit** [comment]
Sure - I'll send a pull request soon!

**Comment by willnorris** [comment]
fixed in e7b0a5b88cb8fb82c0d7c1ce2d969ea3235205e2
