### ISSUE TITLE
My key is slightly off

### ISSUE THREAD

**Issue by kristen1980** [willnorris/imageproxy#129]
I am using the recommended formula for generating a key:

```
package main

import (
    "crypto/hmac"
    "crypto/sha256"
    "encoding/base64"
    "fmt"
)

func main() {
    mac := hmac.New(sha256.New, []byte("secret key"))
        mac.Write([]byte("https://octodex.github.com/images/codercat.jpg"))
        want := mac.Sum(nil)
        fmt.Println("result: ",base64.URLEncoding.EncodeToString(want)) // expect "sXyMwWKIC5JPCtlYOQ2f4yMBTqpjtUsfI67Sp7huXIYY="
}
```

This results in `"XyMwWKIC5JPCtlYOQ2f4yMBTqpjtUsfI67Sp7huXIYY="` vs the key provided in your example `"http://localhost:8080/500,sXyMwWKIC5JPCtlYOQ2f4yMBTqpjtUsfI67Sp7huXIYY=/https://octodex.github.com/images/codercat.jpg"`.  Notice the missing "s" at the front of my key. 

My key doesn't work but yours does. Why am I missing an "s"?

**Comment by willnorris** [comment]
The leading "s" isn't actually part of the signature itself, it's the name of the option, indicating that the remaining string is the actual signature value.  See more at https://godoc.org/willnorris.com/go/imageproxy#hdr-Signature

**Comment by kristen1980** [comment]
that's just weird. even having the key there is weird. should be a query arg.

**Comment by willnorris** [comment]
Not using query strings was an intentional design decision for imageproxy, since it can having [caching implications with various proxies](http://www.stevesouders.com/blog/2008/08/23/revving-filenames-dont-use-querystring/).
