### ISSUE TITLE
Feature for reading image-file from disk

### ISSUE THREAD

**Issue by Gerrel** [willnorris/imageproxy#130]
I'm not familiar with Go, but I would like to have a feature to be able to read image-file from disk which is a shared docker volume.

For example instead of the scheme to be http:// it can be file:// and the path is a file-path on disk.

Is this a feature you also want to incorporate?

* I can probably provide a pull-request if you can give me some pointers where I can properly intercept the request and provide the data.

**Comment by willnorris** [comment]
No, it's not really a feature I'd be interested in adding.  This project is specifically focused on proxying images that are available elsewhere on the web.  If this is a feature you need, I'd encourage you to simply add it in a separate fork of the project.
