### ISSUE TITLE
Cannot vendor the correct version of the package

### ISSUE THREAD

**Issue by LayneChris** [willnorris/imageproxy#135]
Forgive me if it's a stupid question but I am using imageproxy as a package for my project. I am having some issues trying to vendor the package. All other vendored packages work fine. Here's what I do:

```
go get willnorris.com/go/imageproxy
cd ~/go/src/myproject && dep init
```

I then get:
```
...
Using ^0.6.0 as constraint for direct dep willnorris.com/go/imageproxy
Locking in v0.6.0 (3211eeb) for direct dep willnorris.com/go/imageproxy

```
Everything works fine in the project if I don't vendor. Once I vendor I get:
`p.Verbose undefined (type *imageproxy.Proxy has no field or method Verbose)`

Sure enough, comparing the version from go get the one in my vendor folder is out of date. The one in the vendor folder is missing the "Verbose" field which was recently added.

Thanks for everything!

**Comment by LayneChris** [comment]
dep status shows:

```
...
...
willnorris.com/go/imageproxy          ^0.6.0         v0.6.0         3211eeb   v0.6.0   2   

```

**Comment by willnorris** [comment]
The last tagged version of the library is indeed 0.6.0.  You're wanting features that are in the master branch, but haven't yet been included in a release.  So you probably need to change your Gopkg.toml file to use [`branch = "master'`](https://golang.github.io/dep/docs/Gopkg.toml.html#branch).

And yeah, it's probably about time to cut another release, but this is how to get what you're looking for in the meantime.
