### ISSUE TITLE
Release lifecycle and docker image tag

### ISSUE THREAD

**Issue by LoicMahieu** [willnorris/imageproxy#139]
Hi,

I would like to depend directly on the docker image `willnorris/imageproxy` from docker hub. But there is no version tag and only `latest` is available.
In order to prevent futur breaking changes, is it possible to configure docker hub for matching git tag to image tag ?
You can manage it in "Build details" in docker hub.

Thanks!

**Comment by willnorris** [comment]
closing as duplicate of #99
