### ISSUE TITLE
There are no tags for imageproxy versions on dockerhub

### ISSUE THREAD

**Issue by gugu** [willnorris/imageproxy#142]
It will be nice if you add tags in your git repository, so dockerhub will have docker tags for different versions

During last 6 days everyone, who used google cloud in image proxy had their website broken  because of incompatible change

**Comment by willnorris** [comment]
> It will be nice if you add tags in your git repository

Huh?  Releases *are* tagged: https://github.com/willnorris/imageproxy/releases

As for Dockerhub, closing as duplicate of #99
