### ISSUE TITLE
support watermarks as overlays

### ISSUE THREAD

**Issue by dohomi** [willnorris/imageproxy#143]
Thanks for this great tool, it works really great. I would like to know if there is any plan to support watermark images as overlay over the provided images.

Thanks

**Comment by willnorris** [comment]
No plans for adding watermark support.  If and when I refactor imageproxy to [support plugins](https://github.com/willnorris/imageproxy/blob/plugins/doc/plugin-design.md) (no firm plans to do so yet, just thinking through what it would look like), that should be doable via that mechanism.

**Comment by willnorris** [comment]
closing issue, since this is not a feature that will likely ever be implemented in core.
