### ISSUE TITLE
URL signature check failure due to EscapedPath() always use uppercase hex code for urlencoding

### ISSUE THREAD

**Issue by bclow** [willnorris/imageproxy#146]
we have a image  contain Chinese character which will urlencoded as following: 

https://gd.image-gmkt.com/TIME-MAKER-TIME-MAKER-%e8%87%aa%e5%8b%95%e4%b8%8a%e9%8d%8a%e7%9b%92TM-210BCF%e6%b3%95%e6%8b%89%e5%88%a9-%e5%8b%95%e5%8a%9b%e5%84%b2%e5%ad%98%e4%b8%8a%e9%8f%88%e7%9b%92-%e6%97%a5%e6%9c%ac%e9%9d%9c%e9%9f%b3%e9%a6%ac%e9%81%942%e5%85%a5-%e6%90%96%e9%8c%b6%e5%99%a8-%e6%89%8b%e9%8c%b6%e6%94%b6%e7%b4%8d%e6%a9%9f%e6%a2%b0%e9%8c%b6%e7%9b%92/li/320/262/1102262320.g_400-w_g.jpg

please note that we use **lower case** hex character(ie, %e8%87%aa%e5%8b%95...) to encode chinese character in utf-8 form

 imageproxy use  `EscapedPath()` to extract the input path: 
````go
   path := r.URL.EscapedPath()[1:] // strip leading slash`
````

`EscapedPath()`  will convert convert the hex character to upper case(ie, %E8%87%AA%E5%8B%95...) which will cause the signature inconsistent between input path and extracted path.

we might need to consider to use `RawPath` to guarantee the input path consistent with the extracted path. However, on https://github.com/willnorris/imageproxy/issues/115 mentioned that `RawPath` isn't always populated, not sure is there any other good solution to get the original path.

**Comment by willnorris** [comment]
Interesting, definitely seems to be a bug in how we're handling this.  I'll try to dig into it more when I've got a little time.

**Comment by bclow** [comment]
sorry @willnorris,   my bad!  

I just realized that my binary of imageproxy didn't apply the patch on #115 yet. In fact, the patch on #115 (using `EscapedPath()`)  will preserve the original input path, this issue only happen on imageproxy prior to #115 (using `Path` to extract the path).

close this issue as the patch on #115 fixed this issue as well.

**Comment by willnorris** [comment]
oh, that's great to hear!  Thanks for following up.
