### ISSUE TITLE
Not work with image print by php

### ISSUE THREAD

**Issue by laocoi** [willnorris/imageproxy#158]
Hello,

I'm trying put content in to a variable and print it as image with header image/jpg. Everything seem well, but imageproxy can not cache that image.

This is my php code
```
header("content-type: image/jpg");
print_r($content);
```

**Comment by willnorris** [comment]
it's likely that you are inadvertently sending headers that instruct clients not to cache the results.  Can you provide an actual live example URL?  Or at least provide all of the response headers.

**Comment by laocoi** [comment]
Hello, header response as bellow
```
Server: nginx/1.10.2
Date: Tue, 04 Sep 2018 17:11:47 GMT
Content-Type: image/jpg
Transfer-Encoding: chunked
Connection: keep-alive
X-Powered-By: PHP/7.1.21
```

**Comment by laocoi** [comment]
Hello, I'm using on-disk cache, you can check with this image: [https://kche.club/cache/1TjkdvcKUSc113ANj9s8sICEg-QvX7TlW/nhso.jpg](url)

**Comment by willnorris** [comment]
your server isn't telling imageproxy how to cache the image, and so it doesn't.  At the very least you need either an Etag and/or an Expiration date for how long the image can be cached.  Example of how to do each in php:

``` php
header("etag: \"" . md5($content) . "\"");
header('Expires: '.gmdate('D, d M Y H:i:s \G\M\T', strtotime("2 hours")));
```
