### ISSUE TITLE
how to config imageproxy to Space in Digital Ocean?

### ISSUE THREAD

**Issue by chinda** [willnorris/imageproxy#159]
Hello,

I'm looking for self host image process but all my images are store in Digital Ocean Space, please let me know how can I do.

Thanks

**Comment by willnorris** [comment]
I'm not familiar with DO Spaces, but it looks akin to S3?  Do you have public URLs for the images stored there?  If so, you should be able to proxy them just like anything else.  Of course, you'd need to run imageproxy itself on a droplet or somewhere else.
