### ISSUE TITLE
Latest docker release 'forbidden content-type' error

### ISSUE THREAD

**Issue by andybets** [willnorris/imageproxy#164]
I've been using imageproxy for a while now without issues, but when upgrading to the new docker release, the following query doesn't work anymore:
`/50/https://identicon-api.herokuapp.com/bitfinexcw55/50?format=png`

I get `forbidden content-type: "application/octet-stream"`.

Thanks for the great work on this by the way!

**Comment by daohoangson** [comment]
That happened because imageproxy now validates http response content type before processing. By default, it will reject anything that is not `image/*`. See here https://github.com/willnorris/imageproxy#allowed-content-type-list.

You can disable the check easily though:

> Set the flag to an empty string to proxy all requests, regardless of content type.

**Comment by gankgu** [comment]
Please update the doc, Should I use `-contentTypes ""` or `-contentTypes */*` or `-contentTypes *`???

**Comment by gankgu** [comment]
Answer for by comment: use `-contentTypes ""`

For docker compose file use format: 

```
command:
            - "-contentTypes"
            - ""
            - "-addr"
            - "0.0.0.0:80"
```

**Comment by willnorris** [comment]
Closing issue, since it seems to be resolved now. Sorry about the church. For what it's worth, I've recently added a changelog, so these kinds of changes should be easier to spot in the future.

**Comment by xdtianyu** [comment]
For anyone with this problem, you can also use environment variables `IMAGEPROXY_CONTENTTYPES=*/*` or in docker-compose.yml file

```
    environment:
      - IMAGEPROXY_CONTENTTYPES=*/*
```
