### ISSUE TITLE
Cannot transform images stored on Google Cloud Storage

### ISSUE THREAD

**Issue by dvaldivia** [willnorris/imageproxy#168]
I'm running `imageproxy` with the following entry point  on top of a `GKE kubernetes cluster`
entrypoint
```
/go/bin/imageproxy -addr 0.0.0.0:8080 -contentTypes image/*,text/html -cache /tmp/imageproxy -baseURL https://storage.cloud.google.com/MY-BUCKET/
```

However when I try to resize an image, let's say 
```
http://ADDRESS/api/img/100x/VALID_FILE.jpg
```
This throws a google accounts login (note that I had to add text/html to contentTypes so I could see this message)

Error on the logs

```
2019/01/12 07:24:33 error transforming image https://storage.cloud.google.com/MY-BUCKET/VALID_FILE.jpg: image: unknown format
```

The policy for the bucket is public and actually pasting the url in a browser returns the picture, is there any reason GCS would reject the request?

**Comment by dvaldivia** [comment]
This problem originates while trying to server content from `storage.cloud.google.com` domain solution is to serve content from `storage.googleapis.com`

**Comment by willnorris** [comment]
interesting.  Thanks for following up with the solution!  Hopefully others that run into this problem will find this.
