### ISSUE TITLE
Hardware Specification

### ISSUE THREAD

**Issue by ciscoring** [willnorris/imageproxy#169]
Hi. I try to apply this project for my production. However, I cannot find recommended hardware requirements. 

So, I tried to test performance on my vm-4core, 4gb memory. The results of tests are below.

**1. Test secenario**
The server try to resize 4 images by rotation.

img A : png(4.2mb) 2858x1440 → 748x377
img B : png(629kb) 1280x720→ 748x377
img C : png(86.2kb) 336x456 → 222x301
img D : jpg(5.7kb) 94x94 → 94x94

**2. Performance**
img A : about avg 1.6 sec
img B : about avg 0.96 sec
img C, D : about avg 0.3 sec below

total tps : about avg 17.6 tps

Surely, I believe that it becomes better if I use storages like redis(My test assumed that the worst case-not caching).

I will try to test on other device that have higher specification. Before that, could I get recommended hardware specification for production level?

Thank you for your great sharing.

**Comment by willnorris** [comment]
I've not personally done this kind of benchmarking.  

But the kind of hardware you'd need really depends on the size of your operation... how much total traffic, how big of a cache do you want or need, what kind of cache hit does your use of imageproxy tend to have, etc.  For example, lots of traffic with a low cache hit likely means you need more CPU for doing transformations.

Personally, I "use imageproxy in production", but "production" for me is just a couple of personal websites.  So I run imageproxy on a [GCE n1-standard-1](https://cloud.google.com/compute/docs/machine-types) instance that also runs a few other things.

**Comment by ciscoring** [comment]
Thank you for your opinion :)
