### ISSUE TITLE
Log new image sizes (and options) being written to cache

### ISSUE THREAD

**Issue by chredd** [willnorris/imageproxy#17]
This would be great to keep track of what image sizes (and options) are being used by the image proxy. Maybe this would be a flag when starting the service since not everyone are interested by this info.

**Comment by willnorris** [comment]
I'm totally down with adding this, and I don't think it necessarily needs to be hidden behind a flag... it could certainly stand to have a little better logging in general.  The main problem with this though is that imageproxy generally doesn't know when an image is being written to the cache.  That is all handled by the httpcache library and is completely transparent to imageproxy.  We do already set the `MarkCachedResponse` flag on [`httpcache.Transport`](https://godoc.org/github.com/gregjones/httpcache#Transport), but I'll have to experiment a little to see if that is only set for images pulled out of the cache, or if it's also set on newly cached responses.

But even if we aren't able to log when they are added to the cache, I think having a basic access type log would be fine at the info log level.

**Comment by willnorris** [comment]
okay, looks like the `X-From-Cache` header is what we want here.  Take a look at this change is see if it does what you need.

**Comment by chredd** [comment]
Great stuff, works just fine. :+1:
