### ISSUE TITLE
https support

### ISSUE THREAD

**Issue by tungpg** [willnorris/imageproxy#171]
Thank you for your great work. I am new to golang. Could you please tell me how to start the server with https support? 

Thanks so much in advance!

**Comment by tungpg** [comment]
I mean: 
`https://myserverdomain.com/{options}/{remote_url}`

**Comment by willnorris** [comment]
imageproxy doesn't have any native support for serving over https.  The expectation is that you'd run it behind or part of a server that handles that.  See more in #71.  

(I'll close this as a duplicate of #71, and leave that one open to track the feature request)
