### ISSUE TITLE
Conditional Processing

### ISSUE THREAD

**Issue by hirenshah** [willnorris/imageproxy#175]
Do you know if it would be possible to transform a image fetched from a remote http location based on whether there are faces present?

If there are faces present, I would like to smart crop the image down, but if there are no faces then scale to a fixed width and pad any outstanding height (to get a fixed height as well).

**Comment by willnorris** [comment]
imageproxy doesn't currently have any face detection capabilities.  it looks like it would be theoretically possible with https://github.com/esimov/pigo.

**Comment by willnorris** [comment]
closing, since imageproxy doesn't support face detection.
