### ISSUE TITLE
Consider a new release

### ISSUE THREAD

**Issue by Strayer** [willnorris/imageproxy#176]
https://github.com/willnorris/imageproxy/issues/145 is a huge requirement for me, but this change is not yet included in a release. For now I'll have to rely on cloning the repository on a specific commit and building the Docker image, but I'd love to just use an actual release tag or docker image hash.

Sidenote: Thanks for this project – sometimes using external services hosted outside of Europe isn't easy, so having open source software like this is just awesome 👍

**Comment by willnorris** [comment]
working on prepping a new release now

**Comment by willnorris** [comment]
v0.9.0 released: https://github.com/willnorris/imageproxy/releases/tag/v0.9.0

**Comment by willnorris** [comment]
new docker image pushed: https://cloud.docker.com/repository/docker/willnorris/imageproxy

I'm not completely sure why it jumped from 7 MB to 12 MB.  I don't think I added *that* much more code.  Maybe it's some changes in how I'm building the image?  In any event, it's there.
