### ISSUE TITLE
Crop mode - set gravity of crop

### ISSUE THREAD

**Issue by chredd** [willnorris/imageproxy#18]
It would be great if it was possible to set the gravity for the crop.
Something like Top, Bottom, Left, Right or Center(default).

Might be an option like: cropt (top), cropb (bottom), cropl (left) and cropr (right) that is only valid if the image is being cropped.

**Comment by Xample** [comment]
+1

**Comment by sulphur** [comment]
👍

**Comment by willnorris** [comment]
This is now possible with the new crop feature added in #90.  See https://github.com/willnorris/imageproxy/pull/90#issuecomment-326205482 for examples of how it accomplishes it.
