### ISSUE TITLE
-cache on disk not support windows

### ISSUE THREAD

**Issue by Calx-Takeno** [willnorris/imageproxy#181]
I like this project. It's so convenient and great powerful.
I tried
imageproxy -cache "c:\\imagecache"
imageproxy -cache c:/imagecache
ect commands on windows but not working.
Colud you support this on windows?
We have several idle windows server need to use it.

imageproxy version v0.8.0
OS: tested on windows 10 ,I am not sure windows server is OK or not.

**Comment by willnorris** [comment]
@Calx-Takeno would you mind grabbing the latest code in master, and see if my change in 50866d9 fixed this?

**Comment by Calx-Takeno** [comment]
I have used the latest version for a while. It works well.
Thank you!
But I found imageproxy couldn't clean cache by self.
Cache files will be larger and larger over time. So I will clean cache files mannually.
Have it any mechanism to set cache expiration?Cache expiration mechanism will be very useful.
Maybe I missed this feature document notes.

**Comment by Calx-Takeno** [comment]
> @Calx-Takeno would you mind grabbing the latest code in master, and see if my change in [50866d9](https://github.com/willnorris/imageproxy/commit/50866d9f70b091841313818f6ca0a800aedabfd0) fixed this?

I have used the latest version for a while. It works well.
Thank you!
But I found imageproxy couldn't clean cache by self.
Cache files will be larger and larger over time. So I will clean cache files mannually.
Have it any mechanism to set cache expiration?Cache expiration mechanism will be very useful.
Maybe I missed this feature document notes.

**Comment by willnorris** [comment]
thanks for following up, and I'm glad to hear it's working now!

and you're right about the fact that diskcache doesn't do anything to clean old files.  It's certainly something we could add at some point.
