### ISSUE TITLE
[Feature Request] Support BMP format as source image type

### ISSUE THREAD

**Issue by jfcherng** [willnorris/imageproxy#182]
I know it can be weird to use BMP as the source image nowadays but unfortunately I have some BMPs (even worse, they are stored in a MySQL db as blobs...) on an old machine for a historical reason.

Feel free to close this if this is considered valueless.

**Comment by willnorris** [comment]
huh, interesting.  Certainly hadn't ever considered that.

Should be doable without too much trouble since golang.org/x/image/bmp exists.  I don't think I'd likely expose it as a requestable format in the options string, but rather just add support for it if you were to happen to proxy a bmp image.

**Comment by jfcherng** [comment]
> Should be doable without too much trouble since golang.org/x/image/bmp exists. I don't think I'd likely expose it as a requestable format in the options string, but rather just add support for it if you were to happen to proxy a bmp image.

Sure, I do not see a reason to output a BMP. Since the source site is under my control, I am setting a `Etag` and a long `Expires`, proxy BMPs is fine. :+1:

**Comment by jfcherng** [comment]
@willnorris Thank you!
