### ISSUE TITLE
Limit concurrency

### ISSUE THREAD

**Issue by rafamel** [willnorris/imageproxy#185]
Hi there! Excellent work, I just deployed it and worked out of the box without issues. I'm wondering though, whether there is already, or should be, a built in way to limit the number of active connections or, at least, concurrent image processing tasks.

How is it currently handled?

**Comment by willnorris** [comment]
imageproxy itself doesn't do any concurrency... image processing is done in the go routine of the current request.  So the only concurrency happening in the way net/http processes each request in a separate go routine.  

There's not any built-in way to limit the number of requests that a net/http server will accept, but here are several discussion on the topic:

- https://github.com/golang/go/issues/6012
- https://stackoverflow.com/questions/22625367
- https://pauladamsmith.com/blog/2016/04/max-clients-go-net-http.html
