### ISSUE TITLE
Max scaleUp size

### ISSUE THREAD

**Issue by henrikgundersen** [willnorris/imageproxy#188]
Do we have a way to to limit the max scaleUp when the `-scaleUp true` flag is presented?
Having the `-scaleUp true` flag allows users with malicious intent to crash the server by changing the size property in the URL to something extreme like `999999999999999x`.

**Comment by willnorris** [comment]
there isn't currently a maximum size.  Though even if there were (and even without scaleUp), a malicious user could attempt a denial of service attack by requesting a lot of images at different sizes (each one having to be processed and presumably cached).  If your goal is to mitigate those types of attacks, you'd be better served by using[ URL signatures that include the resize options in the signature](https://github.com/willnorris/imageproxy/blob/master/docs/url-signing.md).

**Comment by willnorris** [comment]
closing, since signatures seems the better approach for preventing abuse.
