### ISSUE TITLE
Update mod file to avoid apache thrift dependency error

### ISSUE THREAD

**Issue by abdullah2993** [willnorris/imageproxy#190]
Unable to build a new copy with modules enabled.

**Error:**
```
go: finding git.apache.org/thrift.git v0.0.0-20180902110319-2566ecd5d999
go: finding git.apache.org/thrift.git v0.12.0
go: git.apache.org/thrift.git@v0.12.0: unknown revision v0.12.0
go: git.apache.org/thrift.git@v0.0.0-20180902110319-2566ecd5d999: git fetch -f https://git.apache.org/thrift.git refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in C:\Users\abdullah\go\pkg\mod\cache\vcs\83dba939f95a790e497d565fc4418400145a1a514f955fa052f662d56e920c3e: exit status 128:
        fatal: unable to access 'https://git.apache.org/thrift.git/': Failed to connect to git.apache.org port 443: Timed out
go: error loading module requirements
```
**Reason:** 
Apache thrift repo has moved to github. google api/cloud packages depends on `opencensus-go` which depends upon thrift. The issue is tracked [here](https://github.com/census-instrumentation/opencensus-go/issues/993).

**Fix:**
Add `replace git.apache.org/thrift.git => github.com/apache/thrift v0.12.0` to go.mod

**Comment by willnorris** [comment]
I'm having trouble reproducing this.  What version of go are you running?

**Comment by abdullah2993** [comment]
**go version** `go1.12.9 windows/amd64`

**Comment by abdullah2993** [comment]
I'm not sure how module cache works, but you might be able to reproduce it by deleting thrift from module cache.

**Comment by samvdb** [comment]
apache repo is down: https://status.apache.org/
