### ISSUE TITLE
go test fails on windows

### ISSUE THREAD

**Issue by abdullah2993** [willnorris/imageproxy#191]
Go test fails on windows.

**Error:**
```
2019/09/01 20:14:34 invalid request URL: malformed URL "http://localhost//foo": must provide absolute remote URL 
2019/09/01 20:14:34 request does not contain an allowed host or valid signature: http://bad.test/#0x0            
2019/09/01 20:14:34 error fetching remote image: Get http://good.test/error#0x0: http protocol error             
2019/09/01 20:14:34 content-type not allowed: ""                                                                 
--- FAIL: TestContentTypeMatches (0.00s)                                                                         
    imageproxy_test.go:544: contentTypeMatches(["*"], "text/foobar") returned true, want false                   
FAIL                                                                                                             
exit status 1                                                                                                    
FAIL    willnorris.com/go/imageproxy    0.220s                                                                   
```

**Reason:** 
[contentTypeMatches](https://github.com/willnorris/imageproxy/blob/master/imageproxy.go#L277) uses [filepath.Match](https://godoc.org/path/filepath#Match) as per its documentation `On Windows, escaping is disabled. Instead, '\\' is treated as path separator. ` so if [this](https://github.com/willnorris/imageproxy/blob/master/imageproxy_test.go#L554) is passed to the function it matches on windows. 
On windows, unlike linux `*` matches `text/foobar` but not `text\\foobar` because on windows `\\` is considered a separator not `/`.

**Comment by willnorris** [comment]
I don't have easy access to a windows machine to test this.  I'll see about spinning up a VM somewhere to take a look, but if someone else can get to this first and send a patch, that would be most appreciated.

**Comment by willnorris** [comment]
I suspect the solution may be as simple as switching from [filepath.Match](https://godoc.org/path/filepath#Match) to [path.Match](https://godoc.org/path#Match).  But I'd want to make sure and test that first.
