### ISSUE TITLE
Signature key rotation?

### ISSUE THREAD

**Issue by maurociancio** [willnorris/imageproxy#206]
Hi there,
I'd like to know if there is a way to rotate a signature key. I'd like my image proxy to work with two keys, so while I'm upgrading it on my services, it keeps responding to requests.
Any idea?
Any other solution?
I have a nginx running in front of it, so I can accept other alternatives.
Thanks!

**Comment by willnorris** [comment]
There is not currently any support for key rotation, though it would be pretty simple to add by making `Proxy.SignatureKey` a slice of `[]byte` that are tried in order.  I'll leave this open as a feature request to add that.

On the CLI side, I think I'd just make the `signatureKey` flag repeatable.

**Comment by maurociancio** [comment]
Hey, thanks!
I'll try to add it and submit it as PR. Sounds good? Will you merge it if it looks OK?

**Comment by willnorris** [comment]
Yeah, certainly... You can just make those changes in this pr

**Comment by willnorris** [comment]
err, in a new PR rather.  I was replying from email, and didn't see this was just an issue :)

**Comment by maurociancio** [comment]
Great!

**Comment by maurociancio** [comment]
Hi @willnorris, any chance you could merge this?
