### ISSUE TITLE
http.DefaultServeMux breaks some signed urls

### ISSUE THREAD

**Issue by shahan312** [willnorris/imageproxy#215]
The following commit, currently on master and not released yet, breaks some urls:

Commit: https://github.com/willnorris/imageproxy/commit/3b850734afbc0bca6de0b790a955abc86c951156
`log.Fatal(server.ListenAndServe())` -> `log.Fatal(http.ListenAndServe(*addr, nil))`

An example url that breaks:
https://imageproxy/signature=/https://domain//proxied.png

It breaks, because the DefaultServeMux, performs url sanitization, which redirects the url to:
https://imageproxy/signature=/https:/domain/proxied.png

A possible solution for those that want to run the profiler would be to run the profiler on a different port number, or opt-in into this behavior. Or a change to how the signing is performed. Alternative would be just undo that commit. I'm happy to help out with a PR.

**Comment by shahan312** [comment]
Somewhat related, though slightly different issue: https://github.com/willnorris/imageproxy/issues/212

**Comment by willnorris** [comment]
Are you sure?  ServeMux definitely does clean the URL path, but I don't think it eliminates double slashes.  (Relevant code is [here](https://github.com/golang/go/blob/ccb95b6492ad6e7a7d1a7fda896baee4caffb3b4/src/net/http/server.go#L2212)).  When running imageproxy locally with no webserver in front of it, the double slashes work fine.  It tends to be the webserver in front that removes the slashes (at least in my experience).

**Comment by shahan312** [comment]
In that bit of linked code, it calls `path.Clean`, which according to [docs](https://golang.org/pkg/path/#Clean) eliminates double slashes. I'll also test again, and post results here, need a few days before I can get to it.

**Comment by willnorris** [comment]
You're absolutely right... I missed the `path.Clean` call :)

**Comment by Fieldistor** [comment]
I suggest to use https://github.com/gorilla/mux:

1. Install module - `go get -u github.com/gorilla/mux`
2. modify code in [mail.go](https://github.com/willnorris/imageproxy/blob/master/cmd/imageproxy/main.go#L97) :

```
        r := mux.NewRouter().SkipClean(true).UseEncodedPath()
	r.PathPrefix("/").Handler(p)
	fmt.Printf("imageproxy listening on %s\n", *addr)
	log.Fatal(http.ListenAndServe(*addr, r))
```

Diff:
![image](https://user-images.githubusercontent.com/7847368/78196298-9e65c500-748a-11ea-9ed2-f444c784a9c0.png)

**Comment by willnorris** [comment]
> `r := mux.NewRouter().SkipClean(true).UseEncodedPath()`

Ooh, that's fantastic!  I hadn't realized (or had forgotten) that gorilla/mux has the option to not clean URLs.  I'll certainly give that a shot.
