### ISSUE TITLE
imageproxy Referer

### ISSUE THREAD

**Issue by hellracer** [willnorris/imageproxy#216]
Hi Will,

First of all thanks for this wonderful tool and this is very handy, I hope if you don't mind asking  can we explicitly tell imageproxy to send customize http referer header? so that a remote site will accept imageproxy to download the image. In case my question is not clear, does imageproxy preserved the original Referer header set by the browser and relay this to the remote server where you are getting the image into?, I hope this is clear thanks!

**Comment by hellracer** [comment]
My solution to this was to patch imageproxy and add parameter like -relayReferer https://www.example.com this will set the Referrer header to whatever specified in the command line, I can automatically get the referrer header sent by the browser and relay it, I just have little hesitation because I think by design the author intentionally don't send the header, I can send PR for my little crude hack if anyone interested

**Comment by willnorris** [comment]
I don't seem to recall how intentional I was about not passing along the original referer header.  Off the top of my head, I can't really think of any harm.  It would be a pretty simple matter right around https://github.com/willnorris/imageproxy/blob/edd9dbac2dff871340c136e7b1d316515f6df9db/imageproxy.go#L168

**Comment by hellracer** [comment]
Hi,

Thanks for the reply, If you think there's no harm of relaying the referrer header automatically will going to modify the source, test and send the PR.

**Comment by willnorris** [comment]
I couldn't sleep tonight, so went ahead and coded it up.  😄

**Comment by hellracer** [comment]
I got an error when i try to add parameter in systemd unit file
 
`invalid request URL: malformed URL "/200x200,png/pub/mediafiles/product-images/240/conversion/1-100x100.jpg": must provide absolute remote URL`

```
[Unit]
Description=Image Proxy

[Service]
User=www-data
Environment="AWS_ACCESS_KEY_ID=admin"
Environment="AWS_SECRET_KEY=xxxxx"
ExecStart=/usr/local/bin/imageproxy \
    -addr 192.168.159.5:5050 \
    -includeReferer 1 \
    -allowHosts bucket.abc.com \
    -baseURL https://bucket.abc.com/ \
    -cache memory:1000:4h
Restart=on-abort

[Install]
WantedBy=multi-user.target```

**Comment by willnorris** [comment]
That's certainly odd, given that you are clearly passing a `baseURL` value.  But I don't see how the new `includeReferer` feature could be causing this.  😕

**Comment by hellracer** [comment]
yeah but as soon as i remove includReferer parameter everything backs to normal

**Comment by hellracer** [comment]
I was able to fix the issue by moving the includeReferer parameter to the end, case close!

[Unit]
Description=Image Proxy

[Service]
User=www-data
ExecStart=/usr/local/bin/imageproxy \\
    -addr 192.168.159.5:5050 \\
    -allowHosts bucket.abc.com \\
    -baseURL https://bucket.abc.com/ \\
    -cache memory:1000:4h \\
    -includeReferer 1
Restart=on-abort

[Install]
WantedBy=multi-user.target

**Comment by willnorris** [comment]
That's great that you got it working, though that's really weird that order mattered.  I suspect it may be because it's a boolean flag and you're providing a value?  What happens if you use `-includeReferer` without the `1`?

**Comment by hellracer** [comment]
You are right removing argument "1" from the parameter includeReferer the order does not matter at all

```[Unit]
Description=Image Proxy

[Service]
User=www-data
ExecStart=/usr/local/bin/imageproxy \
    -addr 192.168.159.5:5050 \
    -includeReferer \
    -allowHosts bucket.abc.com \
    -baseURL https://bucket.abc.com/ \
    -cache memory:1000:4h 
    
Restart=on-abort

[Install]
WantedBy=multi-user.target
