### ISSUE TITLE
How to deploy on Centos 7

### ISSUE THREAD

**Issue by thanh858036** [willnorris/imageproxy#217]
I install package `go get willnorris.com/go/imageproxy/cmd/imageproxy` but i run with `imageproxy` and  it show `-bash: imageproxy: command not found`

**Comment by willnorris** [comment]
It's most likely that the binary is getting installed in a directory that's not in your `PATH`.  You can find your GOPATH by running `go env GOPATH`.  imageproxy should be installed in the bin directory under that GOPATH directory.  So if `go env GOPATH` returns `/home/thanh858036/go` then imageproxy should be installed at `/home/thanh858036/go/bin/imageproxy`.
