### ISSUE TITLE
How to run Imageproxy in background

### ISSUE THREAD

**Issue by thanh858036** [willnorris/imageproxy#219]
`copy resulting binary to /usr/local/bin
copy etc/imageproxy.service to /lib/systemd/system and enable using systemctl`
I followed the instructions but couldn't run imageproxy in the background.
![image3759d5402a909a3c.png](https://uphinh.org/images/2020/02/21/image3759d5402a909a3c.png)

**Comment by hellracer** [comment]
Here's my imageproxy.service unit file look like replace User=www-data with `root` if you really want to listen on port (80) and lastly double check if imageproxy binary has `executable` permission



[Unit]
Description=Image Proxy

[Service]
User=www-data
ExecStart=/usr/local/bin/imageproxy \
    -addr 192.168.132.250:5050 \
    -allowHosts bucket.xxx.com \
    -baseURL https://bucket.xxx.com/  \
    -cache memory:1000:4h

Restart=on-abort

[Install]
WantedBy=multi-user.target
