### ISSUE TITLE
Docker Release

### ISSUE THREAD

**Issue by BrianGreenhill** [willnorris/imageproxy#221]
There hasn't been a docker image release in a while. I've deployed a version of master to my own dockerhub namespace as a stop-gap. Would you consider doing a release of the latest changes? Specifically exposing the prometheus metrics is a much-appreciated feature that would be great to have in a release.

**Comment by willnorris** [comment]
just tagged and released v0.10.0

**Comment by BrianGreenhill** [comment]
thank you :)
