### ISSUE TITLE
imageproxy use proxy to request image?

### ISSUE THREAD

**Issue by thanh858036** [willnorris/imageproxy#225]
Hi Will,

First of all thanks for this wonderful tool and this is very handy, I hope if you don't mind asking can we explicitly tell imageproxy to use proxy list to request image? so that a remote site will block ip server if server request many to site

**Comment by Fieldistor** [comment]
Yes, you can setup proxy from Environment.
Currently, by default it uses [https://github.com/willnorris/imageproxy/blob/master/imageproxy.go#L101](DefaultTransport). By default it uses `Proxy: ProxyFromEnvironment,`.
You can setup it using following tip:
```

**Comment by willnorris** [comment]
Thanks @Fieldistor, I wasn't even aware of that myself... that the DefaultTransport would accept those environment variables :)
