### ISSUE TITLE
add support for animated gifs

### ISSUE THREAD

**Issue by willnorris** [willnorris/imageproxy#23]
Example code (under Apache 2.0 license): https://github.com/dpup/go-scratch/blob/master/gif-resize/gif-resize.go

**Comment by willnorris** [comment]
Thanks @dpup for your little [gif-resize](https://github.com/dpup/go-scratch/blob/master/gif-resize/gif-resize.go) example!  I reworked it into a reusable package (58bb2e4ce95e241def262add47953f8ff910c584), and it works great.

Original blob image:

![blob.gif](https://raw.githubusercontent.com/dpup/go-scratch/master/gif-resize/blob.gif)
https://raw.githubusercontent.com/dpup/go-scratch/master/gif-resize/blob.gif

Resized to 200px and rotated 90 degrees:

![blob.gif](https://willnorris.com/api/imageproxy/200,r90,sWepT40QjkBVuX3IDUy87z1xlXCnx5clAOcxnoVHMq30/https://raw.githubusercontent.com/dpup/go-scratch/master/gif-resize/blob.gif)
https://willnorris.com/api/imageproxy/200,r90,sWepT40QjkBVuX3IDUy87z1xlXCnx5clAOcxnoVHMq30/https://raw.githubusercontent.com/dpup/go-scratch/master/gif-resize/blob.gif

**Comment by dpup** [comment]
Nice, glad it worked for you. In practice we have seen some issues with this approach on some gifs, and it will increase the size of the generated image.

**Comment by willnorris** [comment]
Yeah, I noticed that some resized images were a bit larger than I would have expected.  Did you come up with an alternative approach?

**Comment by dpup** [comment]
We just lived with it, but we have started transcoding gifs to video files,
for this and other reasons. I think the algorithm would be something like
this:

1) check every pixel against the previous frame.
2) if the color matches, make pixel transparent.
3) set the frame bounds to be the smallest rectangle that covers
non-transparent pixels.

**Comment by willnorris** [comment]
@dpup: in case you're interested, I achieved considerable file size savings and reduced the noise simply by maintaining the original color palette.  So from your [source shapes.gif](https://raw.githubusercontent.com/dpup/go-scratch/master/gif-resize/shapes.gif) (377K):

Your original resized version is 1.7M:
![shapes](https://raw.githubusercontent.com/dpup/go-scratch/master/gif-resize/shapes.out.fixed.gif)
https://raw.githubusercontent.com/dpup/go-scratch/master/gif-resize/shapes.out.fixed.gif

My updated version that [maintains the original color palette](https://github.com/willnorris/imageproxy/commit/5e9ceeaaf6bd7e44d5818d1a9bafdf51ef571e2e) is 223K:

![shapes](https://willnorris.com/api/imageproxy/250,sdhIVIA2xBZJRhiNgO2CXxyT-iZF84WxUnJSRW8bq8CA/https://raw.githubusercontent.com/dpup/go-scratch/master/gif-resize/shapes.gif)
https://willnorris.com/api/imageproxy/250,sdhIVIA2xBZJRhiNgO2CXxyT-iZF84WxUnJSRW8bq8CA/https://raw.githubusercontent.com/dpup/go-scratch/master/gif-resize/shapes.gif

**Comment by dpup** [comment]
That'll cause resizing artifacts. A pixel's color in the resultant image
will be averaged across multiple pixels in the source image, and the
average may not exist in the palette.

**Comment by willnorris** [comment]
yeah, I did consider that.  Though in practice (at least with images that have large swaths of solid colors like above), the result is still far better than the alternative.  In any event, thanks again for publishing your original tool.  I'll keep playing with a few different approaches (maybe try to compute a closer palette to take pixel merging into account), but I think this is a good 80% solution.

**Comment by willnorris** [comment]
note for future me: go1.5 will expose frame disposal data, the global color palette, and the background color index ([e6092d64](https://github.com/golang/go/commit/e6092d64a7a196e6e228a36eb3b243b379aa2520))
