### ISSUE TITLE
Old go versions dont support ssl properly

### ISSUE THREAD

**Issue by natostanco** [willnorris/imageproxy#24]
might want to serve the binary on plain http because some old version of go (1.2) does not support some ssl, had to manually update to 1.4 to download it

**Comment by willnorris** [comment]
I'm not sure I follow... currently, the imageproxy command does serve only over http (mainly because I've run it behind nginx which does SSL termination for me).  I wouldn't be hard to modify to server https, but it doesn't currently.  Or are you somehow talking about fetching remote images over SSL?

**Comment by natostanco** [comment]
I was talking about the installation

**Comment by willnorris** [comment]
again, I'm still a little confused.  what installation?

**Comment by natostanco** [comment]
`go get willnorris.com/go/imageproxy/cmd/imageproxy`
the get does not fetch properly on old go versions from https

**Comment by willnorris** [comment]
ah, gotcha!  Do you recall the error you got?  I'm wondering if it's something I can tweak in my SSL settings.  Otherwise, I can add a note to the README mentioning the minimum go version needed.

**Comment by natostanco** [comment]
```
go get -v willnorris.com/go/imageproxy/cmd/imageproxy
Fetching https://willnorris.com/go/imageproxy/cmd/imageproxy?go-get=1
https fetch failed.
Fetching http://willnorris.com/go/imageproxy/cmd/imageproxy?go-get=1
import "willnorris.com/go/imageproxy/cmd/imageproxy": http/https fetch: Get https://willnorris.com/go/imageproxy/cmd/imageproxy?go-get=1: x509: certificate signed by unknown authority (possibly because of "x509: cannot verify signature: algorithm unimplemented" while trying to verify candidate authority certificate "COMODO RSA Certification Authority")
package willnorris.com/go/imageproxy/cmd/imageproxy: unrecognized import path "willnorris.com/go/imageproxy/cmd/imageproxy"
```

**Comment by willnorris** [comment]
okay, it seems to be choking on the SHA-384 intermediate certificate from Comodo.  Related discussion:

 - http://bridge.grumpy-troll.org/2014/05/golang-tls-comodo/
 - https://groups.google.com/forum/#!topic/golang-nuts/oK3EBAY2Uig

Even though the mailing list thread makes it sound like it wasn't fixed until go1.4, go1.3rc1 seems to work fine as well (possibly included in all the other TLS changes that happened in that release)

I'll add a note to the README that older versions of go may have trouble installing the package.  Thanks for the report!
