### ISSUE TITLE
Chunked responses?

### ISSUE THREAD

**Issue by schmunk42** [willnorris/imageproxy#263]
Can imageproxy handle chunked responses, eg. for large video files in Safari?
Our video does not load at all, we wanted to use imageproxy as a "simple" streaming proxy, just taking some load off the backend.

**Comment by willnorris** [comment]
I'm not sure if this would work at all, but I can't imagine it would do what you want.  If anything, I suspect that imageproxy would read the large file in chunks from the origin server, cache the whole thing, but then serve it non-chunked.  It was never intended for use cases like this, so doubtful it would work.  It sounds like you really just want a CDN(?)... if so, I think a project more optimized for that kind of use case would likely work better.  Even just using nginx's built-in caching might work well(?) though I'm not sure if it's really designed for really large files.

**Comment by schmunk42** [comment]
Thank you for the answer.
