### ISSUE TITLE
installation no longer works

### ISSUE THREAD

**Issue by joszz** [willnorris/imageproxy#269]
This URL;
willnorris.com/go/imageproxy/cmd/imageproxy

returns a 404.
How to install? 
Also how to upgrade exisiting installs?

**Comment by willnorris** [comment]
The URL https://willnorris.com/go/imageproxy/cmd/imageproxy is expected to return a 404.  To emulate what the `go get` command does, you'd need to fetch https://willnorris.com/go/imageproxy/cmd/imageproxy?go-get=1.  A few years ago, I wrote about this setup: https://willnorris.com/2015/02/go-get-subpackages-nginx/.  (There was an extra redirect happening which [I've gone ahead and removed](https://github.com/willnorris/willnorris.com/commit/e894f8c9bfcf63daded39b12daf782d67810a9b3), though it shouldn't have been causing any problems.)

Can you provide exactly what command you're running and what error you're getting?  

If running `go get`, the `-v` and `-x` flags include verbose and tracing output, respectively.  You may need to remove `$GOPATH/willnorris.com/go/imageproxy`(assuming you don't have any local changes) before runnings these.  For example:

```
% rm -rf ~/go/src/willnorris.com/go/imageproxy
% go get -v willnorris.com/go/imageproxy/cmd/imageproxy
get "willnorris.com/go/imageproxy/cmd/imageproxy": found meta tag get.metaImport{Prefix:"willnorris.com/go/imageproxy", VCS:"git", RepoRoot:"https://github.com/willnorris/imageproxy"} at //willnorris.com/go/imageproxy/cmd/imageproxy?go-get=1
get "willnorris.com/go/imageproxy/cmd/imageproxy": verifying non-authoritative meta tag
willnorris.com/go/imageproxy (download)
```

```
% rm -rf ~/go/src/willnorris.com/go/imageproxy
% go get -x willnorris.com/go/imageproxy/cmd/imageproxy
# get https://willnorris.com/go/imageproxy/cmd/imageproxy?go-get=1
# get https://willnorris.com/go/imageproxy/cmd/imageproxy?go-get=1: 200 OK (0.105s)
# get https://willnorris.com/go/imageproxy?go-get=1
# get https://willnorris.com/go/imageproxy?go-get=1: 200 OK (0.002s)
cd .
git clone -- https://github.com/willnorris/imageproxy /home/willnorris/go/src/willnorris.com/go/imageproxy
cd /home/willnorris/go/src/willnorris.com/go/imageproxy
git submodule update --init --recursive
cd /home/willnorris/go/src/willnorris.com/go/imageproxy
git show-ref
cd /home/willnorris/go/src/willnorris.com/go/imageproxy
git submodule update --init --recursive
WORK=/tmp/go-build159736018
```

**Comment by willnorris** [comment]
@joszz could you confirm if you're still having trouble?  If so, what version of go are you running?

**Comment by joszz** [comment]
@willnorris  I solved the issues, problems on my end....
Sorry and thanks a lot for the support, go is not something I'm that familiar with.
