### ISSUE TITLE
add Dockerfile

### ISSUE THREAD

**Issue by willnorris** [willnorris/imageproxy#27]
I don't run imageproxy inside docker myself, but it appears that at least [some people do](https://registry.hub.docker.com/u/sevki/imageproxy/).  Adding a dockerfile should be pretty simple.

/cc @sevki @etcinit

**Comment by sevki** [comment]
@willnorris should I open a pr for it?

**Comment by willnorris** [comment]
yeah, that'd be great

**Comment by etcinit** [comment]
:+1:

**Comment by willnorris** [comment]
fixed in #29
