### ISSUE TITLE
`signatureKey` help

### ISSUE THREAD

**Issue by benubois** [willnorris/imageproxy#280]
Hi,

Thanks for imageproxy!

I'm getting an unexpected result when trying to use the `-signatureKey` option.

I'm running the docker image like this:

```
$ docker run -p 8080:8080 willnorris/imageproxy -addr 0.0.0.0:8080 -signatureKey "secretKey"
Unable to find image 'willnorris/imageproxy:latest' locally
latest: Pulling from willnorris/imageproxy
a3f7d34f655a: Pull complete 
ac31147b08dc: Pull complete 
5e81671dde55: Pull complete 
947ad098820e: Pull complete 
Digest: sha256:7e4c77d1b64db9152591dbfd8565d5d377eb8a243040efa4e241b97ba94feb1d
Status: Downloaded newer image for willnorris/imageproxy:latest
imageproxy listening on 0.0.0.0:8080
```

Then I'm generating a signature with:

```bash
$ echo -n "https://octodex.github.com/images/codercat.jpg" | openssl dgst -sha256 -hmac "secretkey" -binary | base64 | tr '/+' '_-'
cw34eyalj8YvpLpETxSIxv2k8QkLel2UAR5Cku2FzGM=
```

Which I think means that the image should be available at this URL:

```
http://localhost:8080/cw34eyalj8YvpLpETxSIxv2k8QkLel2UAR5Cku2FzGM=/https://octodex.github.com/images/codercat.jpg
```

However when requesting that URL I see this in the logs:

```
2021/03/29 06:01:22 request does not contain an allowed host or valid signature: https://octodex.github.com/images/codercat.jpg#0x0
```

Am I doing something wrong?

Thanks!

**Comment by benubois** [comment]
I did miss that part! Unfortunately the issue still persists. 

Now the signature shows up in the log:

```
2021/03/29 21:15:43 request does not contain an allowed host or valid signature: https://octodex.github.com/images/codercat.jpg#0x0,scw34eyalj8YvpLpETxSIxv2k8QkLel2UAR5Cku2FzGM=
```

**Comment by willnorris** [comment]
ah, once possible (likely?) option is that you have "secretKey" for your docker command, and "secretkey" (lowercase 'k') for you openssl command.  I'm not able to fully test things at the moment, but that looks like a likely suspect.

**Comment by benubois** [comment]
It works! I was doing too much copying and pasting and not enough reading.

Thanks for the help!

<img width="774" alt="Screenshot 2021-03-29 at 14 48 06" src="https://user-images.githubusercontent.com/133809/112904445-d1db2f80-909d-11eb-82da-6ac98343eb1a.png">
