### ISSUE TITLE
MultiArch docker build for arm support

### ISSUE THREAD

**Issue by macnibblet** [willnorris/imageproxy#296]
Hey,

Would it be possible to add multi arch support to the docker image? Love to see ARM support :)

**Comment by samuelclay** [comment]
Agreed, `docker buildx build` makes multiarch builds easy to implement. I'd love to see that last "amd64" line on NewsBur's docker-compose be replaced in favor of the "arm64" platform my Macbook M1X uses.

**Comment by alpe12** [comment]
Yeah, please. @willnorris

**Comment by willnorris** [comment]
this was fixed a few months ago in a6f541de1b37f9d8bdde5d092c8fe8bbab542b10.
