### ISSUE TITLE
Log files rotation

### ISSUE THREAD

**Issue by Toubib** [willnorris/imageproxy#31]
Hi,

Would it be possible to have a log rotate option (it's generally done with a signal who also reload the configuration) ? I would like to rotate the log files every days at midnight, without restarting the service.

From what I've read, the log file is actually rotated whis this code from glog project:

```
// MaxSize is the maximum size of a log file in bytes.
var MaxSize uint64 = 1024 * 1024 * 1800

func (sb *syncBuffer) Write(p []byte) (n int, err error) {
  if sb.nbytes+uint64(len(p)) >= MaxSize {
    if err := sb.rotateFile(time.Now()); err != nil {
      sb.logger.exit(err)
    }
}
...
```

Would be nice too to change the MaxSize value ...

**Comment by Toubib** [comment]
I've done the job here: https://github.com/Toubib/imageproxy/commit/65be9595a2758470d168376814f8c23e1620427b

Need some tests before pull request.

**Comment by willnorris** [comment]
I wonder if a better approach would just be to switch to github.com/Sirupsen/logrus or something similar?  Do you know if it does log rotation like you're looking for?

**Comment by willnorris** [comment]
I'm going to go ahead and close this in favor of #105.  While I haven't implemented it yet, my intent is to move to the standard log package which writes only to stderr, at which point imageproxy is no longer in the business of caring about log files at all.  There are numerous tools available that could then read imageproxy's stderr and store them in files however the user likes.

**Comment by Toubib** [comment]
Ok.
