### ISSUE TITLE
Serving files from Azure 

### ISSUE THREAD

**Issue by yenilee** [willnorris/imageproxy#325]
Hello, thanks for this project.
I was wondering if there is a way to serve files from cloud like Azure Blob Storage.
I couldn't find how to serve files in the readme, so guess public url is the only way to bring a remote image?
Please let me know if I missed some part of readme or your documents.

**Comment by willnorris** [comment]
yes, imageproxy is a "pull proxy" meaning it proxies images that are already have public URLs.  

There have been requests in the past for serving files off of the local filesystem (which in your case could be a fuse mounted azure storage, for example), but it's not something I've ever added support for.  Someone might have gotten in working on their own, or in a separate fork, I'm not sure.

**Comment by yenilee** [comment]
I see. Thanks for the quick response!
