### ISSUE TITLE
Heroku deploy guide?

### ISSUE THREAD

**Issue by tejasmanohar** [willnorris/imageproxy#34]
Are there some instructions or a basic guide on deploying this service to Heroku?

**Comment by willnorris** [comment]
there are no current instructions for Heroku.  If you end up attempting it and document what you do, maybe add a page on the wiki?

**Comment by tejasmanohar** [comment]
sure, i'm looking right now but not too experienced w/ go and not sure how to deploy the image.

**Comment by tejasmanohar** [comment]
@willnorris can the project be run as a normal go project like `go run ...` and pass in some flags? instead of with the CLI?

**Comment by willnorris** [comment]
I'm not sure what you mean by "normal go project", but sure you can `go run cmd/imageproxy/main.go`.

You may need to add a `Procfile` and maybe make other small changes, but this should certainly be deployable on heroku.

**Comment by runemadsen** [comment]
We are running this on Heroku, and it's working like a charm. 

Here's our `Procfile`:
https://github.com/oreillymedia/imageproxy/blob/master/Procfile

Just follow the "Deploying Go to Heroku" guidelines to vendorize the go packages, commit them to the repo, add this procfile, and you should be all set.

**Comment by tejasmanohar** [comment]
yeah works fine

**Comment by runemadsen** [comment]
FYI, I made a much nicer repo that doesn't have the actual source of the `imageproxy`:
https://github.com/oreillymedia/prototype-imageproxy

**Comment by willnorris** [comment]
feel free to add a link to this in the Deploying section of the readme file

**Comment by runemadsen** [comment]
Done!
