### ISSUE TITLE
How to upgrade existing installation of ImageProxy?

### ISSUE THREAD

**Issue by sunstarjeff** [willnorris/imageproxy#348]
Forgive me if I'm missing the location of the instructions, but how can I upgrade an existing installation of ImageProxy when new versions come out?

**Comment by willnorris** [comment]
there's no real upgrade procedure.  You just replace the binary and start it up.  Or deploy the new docker image, whatever deployment method you're using.  Of the top of my head, I don't think we've ever had any breaking changes, so upgrades should be pretty seamless.

**Comment by sunstarjeff** [comment]
Understood.  Thank you, I appreciate your reply and we love ImageProxy.
