### ISSUE TITLE
Scaling images up

### ISSUE THREAD

**Issue by runemadsen** [willnorris/imageproxy#35]
Hi again.

Another question: We are in a situation where we actually want our images to scale up if they are too small. We have a very particular design, and it breaks the grid if an image is requested to be 1000px, but the original source is 500px and it stays that way.

Would you consider a `scaleup=true` flag that allowed scaling up images?

**Comment by willnorris** [comment]
As a command line flag?  Yeah I think that would be alright.  

Getting it passed in to transformImage might be a little tricky though.  It really should be a property of the `Proxy` object, not on the `Options` struct, which is request specific, but transformImage doesn't current have any visibility into the current Proxy.

**Comment by runemadsen** [comment]
Thanks for the input. I was thinking about it as a command line flag, which seems to make the most sense.

I looked through the code, and I can see what you mean. It seems like the easiest thing would be for the `TranformingTransport` to have a reference to the `Proxy` object settings. What about moving the `Proxy` settings into a separate struct:

```go
type Proxy struct {
  Client *http.Client
  Cache  Cache
  Settings *ProxySettings
}

type ProxySettings struct {
  Whitelist []string
  DefaultBaseURL *url.URL
  SignatureKey []byte
}
```

And then pass this settings object to both the `TranformingTransport` and `Proxy`:

```
client.Transport = &httpcache.Transport{
  Transport:           &TransformingTransport{transport, client, settings},
  ...
}

return &Proxy{
  Client: client,
  Cache:  cache,
  Settings: settings,
}
```

Then the transport could access the settings when calling `Transform()`.

Thoughts? Too much?

**Comment by willnorris** [comment]
yeah, that feels a little heavy weight.

I'm not 100% sure I like this, but I suggest it anyway and see what you think also.  Even though the `Options` struct is request specific, we could add a `ScaleUp` field to it which is set [just before passing it](https://github.com/willnorris/imageproxy/blob/dbf505d1372d6cec891828cbf158e0e93542ea7f/imageproxy.go#L258) to transformImage.  None of the rest of the code in `data.go` would touch that field, so it would never be able to be set via the URL and it wouldn't have any impact on caching, since it would be part of the cache key.

what do you think?

**Comment by runemadsen** [comment]
Yes, that actually sounds great. How will `TransformingTransport` know about the `Proxy` setting though?

**Comment by willnorris** [comment]
ah crap, didn't follow it far enough.  hmm....

**Comment by willnorris** [comment]
I guess maybe TransformingTransport carries a pointer back to its Proxy?  It would be easy enough to restructure NewProxy to do that.

```go
type TransformingTransport struct {
	Transport http.RoundTripper
	CachingClient *http.Client
	Proxy *Proxy
}
```

**Comment by willnorris** [comment]
we already have this cyclical thing going on with the http.Client, so maybe it's not too bad?

**Comment by runemadsen** [comment]
Got it. I'll whip up a PR and you can tell me what you think :)
