### ISSUE TITLE
allow in-memory cache to limit max cache size

### ISSUE THREAD

**Issue by willnorris** [willnorris/imageproxy#4]

**Comment by LukeHandle** [comment]
I can think of ways to limit the number of keys in the cache map, but short of using `runtime.MemStats` I can't think of a way to do it based upon actual memory usage..?

**Comment by willnorris** [comment]
given that we are currently using the `MemoryCache` from the httpcache package, you're right that there's no easy way to track it.  But that [whole implementation is very small](https://github.com/gregjones/httpcache/blob/4fb00a8eec008ffa8ac9ec46a93684dcbb62fc09/httpcache.go#L57-L89), so we could easily copy it over and add in a size counter that is updated on every `Set` and `Delete` call.

I'm just not sure how important this really is.  In practice, the `MemoryCache` should only be used during development, in which case the size shouldn't matter too much.

**Comment by LukeHandle** [comment]
Yea, I had looked at it already and I've worked on another project that used an internal memory cache with some similar ideas.

I like the idea of a memory cache for the proxy and I know that I won't be serving a huge amount of unique resources. Why do you feel it's not appropriate for production?

Of course, I could probably implement a Redis backend for httpcache.

**Comment by willnorris** [comment]
well, I guess there really is no reason why it would be inappropriate for production use, particularly for smaller sites.  I know [these folks](https://github.com/DiscordStudios/imageproxy) are using it with redis, though I don't know much more about what they're doing.

**Comment by willnorris** [comment]
this can be accomplished by switching the in-memory cache to use https://github.com/die-net/lrucache.  We'd also need to update the command line options to allow specifying max size and max age.
