### ISSUE TITLE
A way to limit options to some values

### ISSUE THREAD

**Issue by orian** [willnorris/imageproxy#41]
I have N configs for images and don't want to allow any other options except the whitelisted.
I see two solutions:
 - hmac options in this case a legitimate user (server) can generate any request URL.
 - provide a whitelist to imageproxy either as config or a func `type Whitelist func(ops Options) bool`

What do you think?

**Comment by willnorris** [comment]
Just so I can better understand the use case, why do want to explicitly block options other than your whitelisted set?  What is the concern?

**Comment by orian** [comment]
I want to expose imageproxy to the external world (just behind CDN) I don't want someone to kill the server by crafting requests.

**Comment by orian** [comment]
Please close the issue. I've found it was super easy to write my own server with an imageproxy.Transform, I have a full control there over where data is stored and options ;-)
