### ISSUE TITLE
Default image for HTTP errors

### ISSUE THREAD

**Issue by jmhobbs** [willnorris/imageproxy#47]
Would it be possible to specify a default image to return in the event of an HTTP error, or invalid content type?

**Comment by willnorris** [comment]
are you running this behind a webserver like apache or nginx?  If so, I suspect you could pretty easily do it there by specifying a custom error "page" (though in this case it would be an image).  Would that work?

**Comment by jmhobbs** [comment]
That is an awesome idea!  I'll set it up on nginx.

Thanks!
