### ISSUE TITLE
Entrypoint '/gopath/bin/imageproxy' does not exist

### ISSUE THREAD

**Issue by HasanNizamani** [willnorris/imageproxy#51]
Getting an error when running:

`ERROR: Cannot start container 985dd2dab5a0401a8ec8835638632e4d6bc45b50b6c2c029e04cd43584e9954f: [8] System error: exec: "/gopath/bin/imageproxy": stat /gopath/bin/imageproxy: no such file or directory`

Further investigating I found the ENTRYPOINT written in Dockerfile '/gopath/bin/imageproxy' does not exist in the image.

**Comment by willnorris** [comment]
@sevki: you have any thoughts on what is wrong here?

**Comment by sevki** [comment]
fixed with #52
