### ISSUE TITLE
optimize images

### ISSUE THREAD

**Issue by willnorris** [willnorris/imageproxy#6]
whenever possible, optimize images using something like pngcrush, jpegoptim, etc.

**Comment by takashi** [comment]
@willnorris any updates on this issue?
I'd strongly like to use this feature

**Comment by willnorris** [comment]
nope, no update.  hasn't ever really become an issue for me, so haven't invested any time into it.  I'm not sure that I'd be able to come up with an implementation that I'd be super happy with anyway (having to call out to a separate binary, compile a cgo library, etc)

**Comment by iammichiel** [comment]
Hi there, 

I am quite interested as well in this feature. However, you must understand that optimizing images is a very heavy task for CPU. Plus most PNG optimization algorithms are quite longs in execution time. For example on a 200x200px PNG, with an i7@4.2Ghz, ImageOptim runs for about 5 seconds. 

I don't think this can be done in a proxy such as this project. The best way to optimize the image, would be to optimize the image after upload and then work with the optimized version in this proxy.

**Comment by willnorris** [comment]
closing as unlikely to be implemented.  If ever a pure go library is written for doing this kind of optimization, then we can revisit this.
