### ISSUE TITLE
what is the effect of the parameter inactive in nginx.conf

### ISSUE THREAD

**Issue by cell13** [willnorris/imageproxy#60]
inactive : set the time of the cache to update not visited
description : Actually,it's impossible that the nginx server is not visited enough time.  After the update on the real server, the cache on the nginx server would not be update in time. I don't know how should be useful. I have tried the purge, which is not   convenient

**Comment by noogen** [comment]
https://www.nginx.com/blog/nginx-caching-guide/

> inactive specifies how long an item can remain in the cache without being accessed. In this example, a file that has not been requested for 60 minutes is automatically deleted from the cache by the cache manager process, regardless of whether or not it has expired. The default value is 10 minutes (10m).Inactive content differs from expired content. NGINX does not automatically delete content that has expired as defined by a cache control header (Cache‑Control:max‑age=120 for example). Expired (stale) content is deleted only when it has not been accessed for the time specified by inactive. When expired content is accessed, NGINX refreshes it from the origin server and resets the inactive timer.

Example here of 45 minutes inactive and how to setup cache purge endpoint: https://gist.github.com/noogen/2374a03d2faf6130f937ba774972a083
