### ISSUE TITLE
Bug with transparent animated gifs

### ISSUE THREAD

**Issue by montanaflynn** [willnorris/imageproxy#61]
When I resize a transparent animated gif the result appears to keep the last frame until the loop is done.

### Example:

Source: http://media1.giphy.com/media/TGxuKUoMjea4w/giphy.gif

Resized: https://j.gifs.com/zp5P6O.gif

**Comment by willnorris** [comment]
I suspect this would be solved by changing the animation resize logic to use the algorithm descrbied in https://github.com/willnorris/imageproxy/issues/23#issuecomment-102805309

**Comment by willnorris** [comment]
oh, looks like I'm already tracking this as willnorris/gifresize#1 :)  That was focused on filesize, but I suspect it will also fix this transparency issue.

**Comment by willnorris** [comment]
Here's the image being resized with the fix I just committed: https://willnorris.com/api/imageproxy/200x170,s9GA1t_Si0n2OLm2eGC91AUhs6psMCcw5UmILFIrvvjo/https://media1.giphy.com/media/TGxuKUoMjea4w/giphy.gif

You are also losing the transparent background, which likely means you are using an older (pre 1.5) version of go, or maybe gifs.com is screwing it up.

**Comment by montanaflynn** [comment]
Thanks so much!
