### ISSUE TITLE
Placing behind a reverse proxy

### ISSUE THREAD

**Issue by montanaflynn** [willnorris/imageproxy#65]
In front of all our services I put nginx and use a location directive called `/resize` to proxy traffic to imageproxy. However I cannot get this to work because I get this error:

`invalid request URL: malformed URL "/resize/50x/http://example.com/image.png": must provide absolute remote URL`

I've looked into changing the code in data.go but have been unsuccessful in my attempts, maybe you could point me in the right direction or add a flag to support a URI path prefix?

**Comment by willnorris** [comment]
Can you show me the nginx config that does the proxying? (Or some version of it)

**Comment by montanaflynn** [comment]
```
    location /resize {
      proxy_pass http://127.0.0.1:8080;
    }
```

**Comment by willnorris** [comment]
Try adding a trailing slash to both the location and the proxy_pass:

```nginx
location /resize/ {
    proxy_pass http://127.0.0.1:8080/;
}
```

-----

The relevant nginx docs for this are a little confusing:

> If the proxy_pass directive is specified with a URI, then when a request is passed to the server, the part of a normalized request URI matching the location is replaced by a URI specified in the directive:
> ```nginx
> location /name/ {
>     proxy_pass http://127.0.0.1/remote/;
> }
> ```
> If proxy_pass is specified without a URI, the request URI is passed to the server in the same form as sent by a client when the original request is processed, or the full normalized request URI is passed when processing the changed URI:
> ```nginx
> location /some/path/ {
>     proxy_pass http://127.0.0.1;
> }
> ```

The distinction between the value being "specified with a URI" or not is really just the path portion of the URI.

**Comment by montanaflynn** [comment]
Thanks for the quick reply and workaround. After making the change it seems to result in 
three slashes showing up in the target image URL:

https://127.0.0.1/resize/50x/https://upload.wikimedia.org/wikipedia/en/a/a9/Example.jpg

`error fetching remote image: Get https:///upload.wikimedia.org/wikipedia/en/a/a9/Example.jpg#0x0,scaleUp: Get https:///upload.wikimedia.org/wikipedia/en/a/a9/Example.jpg: http: no Host in request URL`

**Comment by willnorris** [comment]
You can see my nginx config at https://github.com/willnorris/willnorris.com/blob/master/etc/nginx-shared.conf#L95-104

I actually don't have the trailing slash in the proxy_pass either, but based on what you're saying, maybe I shouldn't?  That was a recent thing I learned for a different project, and thought it might help here, but perhaps not.

**Comment by branimir93** [comment]
I lost 12 hours of my life trying to set it up the right way :D Had all the same problems you did.. And this is the only solution as in @willnorris config (using IF for capturing original url)

```
location ~ /img/ {
    if ( $request_uri ~ ^/img/(.*)$ ){ }
    proxy_pass http://imageproxy/$1;

    # cache & default image
    proxy_cache            imgcache-local;
    proxy_cache_valid any      24h;
    proxy_cache_use_stale  error timeout invalid_header updating http_500 http_502 http_503 http_504 http_403 http_404;
    proxy_intercept_errors on;
    error_page 400 401 402 403 404 405 406 407 408 409 410 411 412 413 414 415 416 417 418 420 422 423 424 426 428 429 431 444 449 450 451 500 501 502 503 504 505 506 507 508 509 510 511 =200 /static/default-image.png;
}
```

**Comment by montanaflynn** [comment]
I think that a more generic solution could be changing [data.go#L241-L257](https://github.com/willnorris/imageproxy/blob/master/data.go#L241-L257) to allow for preceeding paths.  If I didn't want to use `nginx` but were to put imageproxy behind a router I think this would be necassary.

**Comment by willnorris** [comment]
And then pass the prefix to be stripped as a command line flag or something?

**Comment by montanaflynn** [comment]
Yep that's what I was thinking.

**Comment by willnorris** [comment]
You said "if you were to put imageproxy behind a router".  Is this an actual use case for you?  I'm not really interested in adding a bunch of additional flags to handle hypothetical deployment scenarios.  

I did just commit a1af9aa though, which removes the need for the $request_uri matching inside nginx.

**Comment by montanaflynn** [comment]
Definitely a real use case, we're moving away from nginx towards using a golang reverse proxy which allows us to add custom middleware and have better http2 support.

**Comment by willnorris** [comment]
then why not just use http.StripPrefix in the go proxy?

**Comment by montanaflynn** [comment]
I hadn't heard of that

**Comment by willnorris** [comment]
https://golang.org/pkg/net/http/#StripPrefix

**Comment by noogen** [comment]
If you're using nginx, you don't need to use if statement to match.  You can put the regex on the location line itself? 

```
location ~ /resize/(.*) {                    
...
		proxy_pass http://127.0.0.1:8080/$1?$args;
...
	}
```

**Comment by willnorris** [comment]
@montanaflynn could you confirm if this is still an issue for you?

Path rewriting is a pretty standard feature of most any web proxy, so I'm pretty sure this should be doable in the config for whatever proxy you're standing up in front of imageproxy.

**Comment by montanaflynn** [comment]
@willnorris this is not an issue for us anymore

**Comment by willnorris** [comment]
I'm doing exactly that on my site: running this behind an nginx proxy that is configured for http2.  Config is at https://github.com/willnorris/willnorris.com/blob/ea55901e29648074df459da964394c0f6b6ba23a/etc/nginx-shared.conf#L97

**Comment by dvaldivia** [comment]
I had to debug for a while before I discover that if you use `listen 80 http2` on nginx, proxy_pass doesn't work, I wonder if there was something else to try.

What I ended up doing is creating an additional nginx only for the imageproxy, since I'm planning to serve the images from it's own url I don't mind this approach, but I'm sure other users could use the mix and match http + http2 proxy_pass

**Comment by willnorris** [comment]
http2 requires SSL, which I suspect you're not using if listening on port 80.

**Comment by nhvu95** [comment]
In my case, I ran them in the Docker. Please remember to add '/' at the end of the location and the URL of proxypass. If we missing it proxypass will also get request which include `/img/` like `/img/200/some.image.png` and it will never work
`location /img/ {
    proxy_pass http://imgproxy:8080/;

    # Increase proxy timeout settings
    proxy_connect_timeout 60s;
    proxy_send_timeout 60s;
    proxy_read_timeout 60s;
}`
