### ISSUE TITLE
invalid request URL: malformed URL "http://[someurl]/": too few path segments

### ISSUE THREAD

**Issue by alexhunsley** [willnorris/imageproxy#69]
I'm trying out imageproxy via safari on Mac OS X 10.10.5, Go version is `go version go1.6.2 darwin/amd64`

If I set the system proxy to localhost:8080 and attempt to load http://news.bbc.co.uk in Safari, the browser shows:

`invalid request URL: malformed URL "http://news.bbc.co.uk/": too few path segments`

The terminal where I ran imageproxy from shows a lot of output like the following:

```
Alexs-Mac-Pro:~ alex$ /Users/alex/Documents/go/bin/imageproxy -cache  ~/Documents/imagecache/
imageproxy (version HEAD) listening on localhost:8080
2016/06/27 17:29:25 http: panic serving 127.0.0.1:57575: runtime error: slice bounds out of range
goroutine 21 [running]:
net/http.(*conn).serve.func1(0xc820094200)
    /usr/local/go/src/net/http/server.go:1389 +0xc1
panic(0x437100, 0xc820010090)
    /usr/local/go/src/runtime/panic.go:443 +0x4e9
willnorris.com/go/imageproxy.NewRequest(0xc82010e000, 0x0, 0xc820073440, 0x0, 0x0)
    /Users/alex/Documents/go/src/willnorris.com/go/imageproxy/data.go:242 +0x88f
willnorris.com/go/imageproxy.(*Proxy).ServeHTTP(0xc82006a620, 0xa49dc0, 0xc820075ba0, 0xc82010e000)
    /Users/alex/Documents/go/src/willnorris.com/go/imageproxy/imageproxy.go:101 +0x26a
net/http.serverHandler.ServeHTTP(0xc820094180, 0xa49dc0, 0xc820075ba0, 0xc82010e000)
    /usr/local/go/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc820094200)
    /usr/local/go/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
    /usr/local/go/src/net/http/server.go:2137 +0x44e

```

I get exactly the same results using Chrome too.

**Comment by willnorris** [comment]
When you say that you attempt to load http://news.bbc.co.uk, what is the exact URL that you are loading?

**Comment by alexhunsley** [comment]
Exactly that - `http://news.bbc.co.uk` - no trailing slash or anything after the .uk

**Comment by alexhunsley** [comment]
Just tried again. The terminal also sometimes produces errors such as:

`E0627 18:31:18.791864   87280 imageproxy.go:104] invalid request URL: malformed URL "http://www.bbc.co.uk/emp/network_status.txt?cb=1467048678788": must provide absolute remote URL`

**Comment by willnorris** [comment]
huh?  If you're just loading "http://news.bbc.co.uk", then you're not using imageproxy at all.... you're just trying to load the BBC's website directly.  Or are you doing some kind of weird web proxy in your OS X network settings?  Otherwise, you're URL should be begin with http://localhost:8080/ or wherever you are running the proxy.

**Comment by alexhunsley** [comment]
Yes, I'm setting the http proxy In Mac OS to localhost port 8080 for http://

**Comment by alexhunsley** [comment]
Is imageproxy just for images? I got the impression it was a web proxy that could cash/alter images, but obviously I could be very wrong about that.

**Comment by willnorris** [comment]
yeah, it's just for images.  It's designed to have the URL of the image appended to the proxy server address.  So something like:

<http://localhost:8080/http://news.bbc.co.uk/>

**Comment by alexhunsley** [comment]
Ah sorry, my bad then!
