### ISSUE TITLE
s3 cache returns AWSAccessKeyID error 

### ISSUE THREAD

**Issue by themetric** [willnorris/imageproxy#70]
I'm getting an error from AWS S3 that has been very tricky to debug: 

```
2016/07/11 22:42:35 s3util.Create failed: unwanted http status 403: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>InvalidAccessKeyId</Code><Message>The AWS Access Key Id you provided does not exist in our records.</Message><AWSAccessKeyId></AWSAccessKeyId><RequestId>3BA092B6EBA3975B</RequestId><HostId>pDi5vYDyJszinDnRtboHuATtH80kOv67PXjvI08j/pYIMaWjsIw8ggHQ9t86ta4NI5o+Q0vFzNs=</HostId></Error>"
```

Inside the same docker container with the environment variables, set this command works: 

```
root@4cd96af5dc13:/go/src/app# aws s3api put-object --bucket image-cache --key hello --debug
```

Here's my startup command: 

```
/go/bin/imageproxy -addr 0.0.0.0:8080 -cache s3://s3-us-west-2.amazonaws.com/image-cache
```

I setup an IAM user and set the 2 required environment variables.  The user has full S3 access, I attached every S3-related policy I could find.  

Tried all the fixes suggested in https://github.com/willnorris/imageproxy/issues/58

**Comment by noogen** [comment]
I found your bucket on image-cache.s3-eu-west-1.amazonaws.com.   Look like your issue was wrong referencing of the bucket region and you resolved this already?  I just hit your s3 bucket and looks like you have it working?   You may want to decline public access to your bucket.

**Comment by themetric** [comment]
@noogen thanks for your help, that actually isn't the full bucket name, I removed part of the name for privacy.  But I think you're on to something with the region.  What's strange is that the AWS S3 docs say that S3 does not have a region but the construction of the URL seems to require it.  

My URL while browsing in the web is: 

https://console.aws.amazon.com/s3/home?region=us-west-2#&bucket=example-image-cache&prefix=

and then I would think the S3 URL should be: 

s3://s3-us-west-2.amazonaws.com/example-image-cache

**Comment by noogen** [comment]
Your error is relating to permission.  Have you check your environment variables?  aws cli use different environment variable can the cache module.

AWS CLI:  AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY
VS: AWS_ACCESS_KEY_ID and AWS_SECRET_KEY

Reference: https://github.com/willnorris/imageproxy/blob/master/vendor/sourcegraph.com/sourcegraph/s3cache/s3cache.go

**Comment by themetric** [comment]
I noticed that too and already have both set as environment variables as seen here (truncated for privacy): 

![screen shot 2016-07-28 at 4 08 05 pm](https://cloud.githubusercontent.com/assets/1435186/17232526/81b34d5e-54dd-11e6-935e-c90e91d9f5de.png)

**Comment by noogen** [comment]
And your user PUZJQA... permission look something like this? 
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "s3:ListAllMyBuckets",
        "s3:GetBucketLocation"
      ],
      "Resource": "arn:aws:s3:::*"
    },
    {
      "Effect": "Allow",
      "Action": "s3:*",
      "Resource": [
        "arn:aws:s3:::BUCKET-NAME",
        "arn:aws:s3:::BUCKET-NAME/*"
      ]
    }
  ]
}
```

**Comment by themetric** [comment]
Correct, the IAM user associated with those creds should have full S3 access. 

![screen shot 2016-07-28 at 4 31 21 pm](https://cloud.githubusercontent.com/assets/1435186/17232949/d08ed30a-54e0-11e6-8691-44e1acae8e00.png)

**Comment by noogen** [comment]
Well, I'm pretty much out ideas.  
1) Have you try wrapping the URL in single quote?  's3://blah blah/bucket' because sometime command line parsing can be tricky especially when there are dashes.
2) Can you tell me the docker image you're using and the command you're using - obfuscate the bucket if you want.   It should work running locally; that way, I can see if I can troubleshoot the command.

**Comment by noogen** [comment]
AWS S3 browser is *NOT* region specific.  You can navigate to all buckets from all regions in the browser and your URL still denote the region you're currently in.  
```
https://console.aws.amazon.com/s3/home?region=us-west-2#&bucket=example-image-cache&prefix=
```
 does not necessarily means that your s3 url should be:
```
s3://s3-us-west-2.amazonaws.com/example-image-cache
```

**Comment by willnorris** [comment]
given the age of this issue, I'm going to assume it's obsolete at this point.  If you still need help, please feel free to reopen.
