### ISSUE TITLE
Blacklisting private ip addresses/hosts

### ISSUE THREAD

**Issue by maurociancio** [willnorris/imageproxy#72]
Hi there,
I'd like to blacklist private ip addresses or hosts, so it won't request it self and other services running in the same private network.
Does it support some kind of blacklist?
I tried this and it worked: http://localhost:8080/http://172.17.0.1/html/ being 172.17.0.1 the ip address of the host running docker.
Thanks!

**Comment by willnorris** [comment]
deny lists added in #85
