### ISSUE TITLE
S3 cache: The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.

### ISSUE THREAD

**Issue by alexeyilchuk** [willnorris/imageproxy#74]
Hi,

I am getting the following error durring saving file to S3 cache:
`s3util.Create failed: unwanted http status 400: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>InvalidRequest</Code><Message>The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.</Message>`

I found the same error in another repos and it seems that it's related to the buckets that are placed in Frankfurt: http://stackoverflow.com/questions/26533245/the-authorization-mechanism-you-have-provided-is-not-supported-please-use-aws4

**Comment by willnorris** [comment]
I've now switched over to the official aws-sdk-go package, which supports the newer v4 authentication method.  I've tested it myself with a bucket in Frankfurt, and everything seems to work well.
