### ISSUE TITLE
Supports HTTP status 504 when source web server exceeds timeout.

### ISSUE THREAD

**Issue by hey-jude** [willnorris/imageproxy#75]
I need timeout option if source image web server response is too long.

Is it possible?

**Comment by willnorris** [comment]
imageproxy doesn't currently support that, but yeah it'd certainly be possible.  If you or someone else want to take a stab at it, I'd be happy to review, otherwise I may try implementing myself... it definitely sounds like a good idea.

**Comment by hey-jude** [comment]
👍 

By the way, what is unit of timeout duration? Second, or ms.?

**Comment by willnorris** [comment]
(oops, just saw your last comment...)

The user specifies the unit.  See [flag.Duration](https://golang.org/pkg/flag/#Duration) and [time.ParseDuration](https://golang.org/pkg/time/#ParseDuration) for details.
