### ISSUE TITLE
Information request

### ISSUE THREAD

**Issue by pavelvasev** [willnorris/imageproxy#76]
Dear project developers!

* Does this software works in multi-stream model, like nodejs? E.g. may it manipulate many simultaneous requests like nodejs? (sorry i don't know `go` server model)

* Which software it use for resize? Imagemagics, vips, or some go facilities?
* Does it supports only png, jpeg, gif, or all other formats too?..

Thanks a lot!

**Comment by willnorris** [comment]
> Does this software works in multi-stream model, like nodejs? E.g. may it manipulate many simultaneous requests like nodejs? (sorry i don't know go server model)

Go's `http.Server` handles individual requests in separate go routines, so they should not block each other.

> Which software it use for resize? Imagemagics, vips, or some go facilities?

It uses a pure go implementation: https://github.com/disintegration/imaging

> Does it supports only png, jpeg, gif, or all other formats too?..

Right now, it only support those three.  I'd love to add webp support, but https://godoc.org/golang.org/x/image/webp currently only support image decoding, not encoding.

**Comment by pavelvasev** [comment]
Thank you for fast and accurate response! One more question - does image formats fixed in `transform.go` via import and case statements in Transform routine?..

**Comment by willnorris** [comment]
If I understand what you're asking, then yes.  Support for different image formats is done by importing the package (which registers it with `image` package, and adding support for it in the case statement in `Transform`.  Any other format that can register itself with `image` could be added pretty easily by doing those two things.

In some cases, there is also some additional format specific logic.  For example, gif images use the `gifresize` package which has support for animated gifs, and jpeg images support the additional `quality` option.

**Comment by bennidhamma** [comment]
Is there any chance you could decode webp but encode as a jpg or png?

**Comment by willnorris** [comment]
> Is there any chance you could decode webp but encode as a jpg or png?

Wouldn't that largely defeat the purpose of using webp?  In that it's more compact that jpg and png?

**Comment by bennidhamma** [comment]
For our use case, we have users uploading photos into our system which we then want to serve to the world. Some of our users happen to use webp formats. But some of our users view our site in Firefox and Safari, neither of which currently support webp.

I'd love to see a case where users could upload a webp image, to save them the time of having to transcode on their end, but maximizing adoption by serving jpgs.

And, since google released Guetzli, we could get pretty some impressive compression (35% better than existing jpg compression):

https://github.com/chai2010/guetzli-go

I think if imageproxy could read in go, and export as guetzli-compressed jpgs, that would be a pretty good win, no?

**Comment by willnorris** [comment]
guetzli-go uses cgo, which I really don't want to take on.

I've filed a separate bug (#88) to track adding webp support, with some additional notes for whoever implements it.

**Comment by willnorris** [comment]
The original questions in this issue have been answered, as well as decoding support for webp added.  For the time being, I still don't want to add any dependencies that require cgo, so that eliminates guetzli-go.  Given that, I'll close this issue for now.
