### ISSUE TITLE
Improve imageproxy performance

### ISSUE THREAD

**Issue by aaronorosen** [willnorris/imageproxy#81]
I have imageproxy setup and working and it seems to work great. My only problem is it seems to be serving images somewhat slowly when say 30+ images at a time are requested at it at once. I was wondering what type of concurrency model imageproxy uses?

**Comment by willnorris** [comment]
imageproxy doesn't do any concurrency itself beyond what go's http server already does.

**Comment by aaronorosen** [comment]
Does the http server it users implement concurrency?I guess i could try running multiple of them on the same machine behind a LB to see what type of performance gain I can get out of a single box.

**Comment by willnorris** [comment]
Each inbound request is handled in a separate go routine.

**Comment by mbn18** [comment]
Hi,
It takes around `25ms` to pull an image from `Nginx` server that is on the same host.
And it does not matter if the file is cached by `imageproxy` or not. On each request it reach the `Nginx` server and get a `304` response.

Is it possible to add `TTL` or something similar? It takes 2-4ms to get the image directly from the `Nginx` server.

**Comment by datasage** [comment]
I found that it will crash on 4 GB of memory if 40-50 images are requested at once. So to limit the requests to the imageproxy, i pass everything through haproxy and limit backend connections.

In front of that, i use a cloudfront distribution with very long expire headers.

With this, the initial request will be slow, but all subsequent requests will come directly from cloudfront. With this setup, only 3-4% of image requests actually hit imageproxy.

**Comment by willnorris** [comment]
closing, as the original questions seems to have been answered.
