### ISSUE TITLE
404 - File or directory not found for specific image

### ISSUE THREAD

**Issue by lucaswxp** [willnorris/imageproxy#84]
I have the following image:

http://www.casasbahia-imagens.com.br/audio/audioaparelhos/CaixasAcusticas/11103116/764655087/Caixa-de-Som-Portatil-Lenoxx-CA-302-Compacta-com-Entrada-Micro-SD-USB-Radio-FM-e-Bateria-Recarregavel-–-40W-11103116.jpg

I get 404 when using imageproxy like this:
http://www.reduza.com.br/img-remote/80x/http://www.casasbahia-imagens.com.br/audio/audioaparelhos/CaixasAcusticas/11103116/764655087/Caixa-de-Som-Portatil-Lenoxx-CA-302-Compacta-com-Entrada-Micro-SD-USB-Radio-FM-e-Bateria-Recarregavel-–-40W-11103116.jpg

It does work with other images, for instance:
http://www.reduza.com.br/img-remote/80x/https://images-soubarato.b2w.io/produtos/01/00/item/126831/7/126831715_1GG.jpg

**Comment by willnorris** [comment]
your second link no longer 404s, so I'm going to assume you managed to fix this on your end.  If you're still having issues, please feel free to reopen the issue.
