### ISSUE TITLE
Production specs

### ISSUE THREAD

**Issue by maurociancio** [willnorris/imageproxy#86]
Hi there!
I'd like to know where you run the image proxy binary. What specs, provider, etc?
Thanks you!

**Comment by willnorris** [comment]
personally, I run it on Google Compute Engine on an n1-standard-1 instance.  That machine serves a few static sites and a couple of (relatively small) WordPress sites, as well a few random services like my personal camlistore instance.

**Comment by maurociancio** [comment]
Thank you!

**Comment by uhlhosting** [comment]
@willnorris is  there any documentation  on integrating it with WordPress?

**Comment by willnorris** [comment]
> @willnorris is there any documentation on integrating it with WordPress?

No, not really.  The closest thing is the [phaser plugin](https://github.com/willnorris/phaser) I wrote many years ago, forked from photon.  As you can see in the commit history, it's 9+ years old, so very well may not work at al any more.  But it's possible you could fork [a more recent version of photon](https://github.com/search?q=repo%3AAutomattic%2Fjetpack%20photon&type=code), and adapt it to point at an imageproxy instance.
