### ISSUE TITLE
Can't resize a certain gif

### ISSUE THREAD

**Issue by montanaflynn** [willnorris/imageproxy#87]
For some reason this gif will not resize: 

https://cdn.gifs.com/easel/0.4.5/assets/stickers/animated/money.gif

**Comment by willnorris** [comment]
resizes fine for me: https://willnorris.com/api/imageproxy/100x,s0BGVI0GzTtwn-fyIz_l2Vjf39t88eLW3_fz1kZjy5v0=/https://cdn.gifs.com/easel/0.4.5/assets/stickers/animated/money.gif (though the animation gets messed up)

Maybe something got fixed since you originally filed this?

**Comment by willnorris** [comment]
Closing old issue.  Please reply and/or reopen if you still experience the problem.
