### ISSUE TITLE
Imageproxy super slow for certain images

### ISSUE THREAD

**Issue by T-Grave** [willnorris/imageproxy#91]
I have imageproxy setup on a dedicated VPS instance with Disk Caching enabled. When I use the proxy, I can clearly see the different sizes being cached on the disk.

My proxy is setup behind an NGINX proxy, currently using HTTP2, but I had the same issue before I switched my ngnix conf to use HTTP2.

The problem is, some of these images take almost 4 full seconds to load in a separate browser tab (when querying 10-20 images at the same time on a single page, these images need almost 12 seconds to load) while others only need 60-100ms to load.

Example of slow loading image (**3-4s for 20kb**):
https://img1.vgcomputers.be/300,fit/ed6e364d1a5788f7f5f90256e515cc69.jpeg

Example of fast loading image (**60-100ms for 28kb**):
https://img1.vgcomputers.be/400,fit/6f58d20c93da5a34e75bc74f96f04f23.jpeg

Any idea what might be causing this? I've aready tried switching between VPS providers, clearing the disk cache, recreating the docker container, tweaking nginx settings but no real difference.

**Comment by noogen** [comment]
Would you happen to have a link to several original image that is slow so someone can troubleshoot from the imageproxy code side?

**Comment by willnorris** [comment]
Can you also check your INFO logs and confirm that the images are actually being served out of the cache?  You should see something like:

```
I0601 18:06:53.335082   27469 imageproxy.go:132] request: https://willnorris.com/2015/02/DSC07158.jpg#300x0 (served from cache: true)
```

**Comment by willnorris** [comment]
@T-Grave: any update on your end that could help debug this?  As @noogen noted, it would be helpful to have the original image URL so that other can try to reproduce the behavior.

**Comment by T-Grave** [comment]
My apologies for the late response, been busy and solved my problem by switching to a different service for now.

But I'll see what I can do to help out debugging.

The original image is located at: https://img0.vgcomputers.be/ed6e364d1a5788f7f5f90256e515cc69.jpeg

I will check the INFO logs tomorrow and report back as soon as I do.

**Comment by willnorris** [comment]
Thanks for your willingness to help even though you've switched services.  Just from some really brief experimenting, my best guess is that maybe you're not caching the results?  What flags are you passing to imageproxy when you start it?

From my quick experimenting..
 - loading https://img0.vgcomputers.be/ed6e364d1a5788f7f5f90256e515cc69.jpeg from a cold cache takes ~3.5s
 - initial load [through my imageproxy server](https://willnorris.com/api/imageproxy/sIlLT6yyTKeIjRB8YXwLSGuByWkFCSJ0xJHgSjLbdM8k/https://img0.vgcomputers.be/ed6e364d1a5788f7f5f90256e515cc69.jpeg) with no transformation similarly takes ~3.5s
 - subsequent loads through my imageproxy server with no transformation take ~1.8s
 - initial load [through my imageproxy server with "300,fit" options](https://willnorris.com/api/imageproxy/300,fit,sIlLT6yyTKeIjRB8YXwLSGuByWkFCSJ0xJHgSjLbdM8k/https://img0.vgcomputers.be/ed6e364d1a5788f7f5f90256e515cc69.jpeg) takes ~3.5s
 -  subsequent loads through my imageproxy server with "300,fit" options take ~250ms

So the best thing that I can determine from that is that the origin server is a little slow in serving the image, but once the resized version is properly cached, it's served pretty fast.  Do you recall if you were using a cache with your imageproxy instance?

**Comment by T-Grave** [comment]
Yes, I'll see later today if I can find the exact start command, but I'm pretty sure I was caching to disk and for 90% of the images I was able to confirm caching was working because they needed about 1s on initial load and less than 100ms on hot load (browser cache disabled ofcourse). As I've said I also tried fixing the issue by clearing the folder containing the cache, but the same images gave me the same problem again.

**Comment by willnorris** [comment]
closing old issue.  please reopen or comment if anyone else is seeing similar behavior.
