### ISSUE TITLE
Massive size increases while even serving smaller or lower quality images

### ISSUE THREAD

**Issue by SkPhilipp** [willnorris/imageproxy#93]
Hey,

We're testing image proxy currently at our company, and we see the following on files served through it:

![screen shot 2017-05-30 at 11 45 02](https://cloud.githubusercontent.com/assets/1235612/26719362/812dc5fe-4784-11e7-88b0-3a9b06387260.png)

You can see here on the left, the original image is ~176KB. Served through image proxy at its original size and full quality, it is ~631KB.

They only appear to start getting smaller at about q40, at which point the image has pretty bad JPEG artifacts visible all over. When using just size we have to make our images appox at least 1/3rd the original size.

Meaning using this project without lowering size or quality significantly, makes our images up to 4x bigger, which kind of beats the purpose of this.

**Comment by willnorris** [comment]
Can you provide the URL of that test image so I can try to replicate the results?

**Comment by willnorris** [comment]
Are you still seeing this behavior?  As noted above, can you provide the URL of the test image so I can try to reproduce this?

**Comment by willnorris** [comment]
closing old issue with no response.
