### ISSUE TITLE
imgix.com images won't load

### ISSUE THREAD

**Issue by arjunskumar47** [willnorris/imageproxy#98]
Any images hosted on imgix.com proxy won't load and gives the following error.

`error fetching remote image: Get https://ksr-ugc.imgix.net/assets/016/599/130/ccc513e82963f1b8ddcb0ef467debbcb_original.jpg?crop=faces&w=560&h=315&fit=crop&v=1497226859&auto=format&q=92&s=347e6bca8855daa60d17b569ea67e886#0x0: Get https://ksr-ugc.imgix.net/assets/016/599/130/ccc513e82963f1b8ddcb0ef467debbcb_original.jpg?crop=faces&w=560&h=315&fit=crop&v=1497226859&auto=format&q=92&s=347e6bca8855daa60d17b569ea67e886: x509: certificate signed by unknown authority`

or 

`error fetching remote image: Get https://aboutme.imgix.net/background/users/j/h/a/jhancoc_1498077342_404.jpg#0x0: Get https://aboutme.imgix.net/background/users/j/h/a/jhancoc_1498077342_404.jpg: x509: certificate signed by unknown authority`

Any thoughts ?

**Comment by willnorris** [comment]
It means that the certificate authority that imgix.net is using is not in your set of trusted roots.  Are you able to successfully load other https URLs or are they all giving this error?  Where are you running imageproxy?  For example, inside a docker container, a regular linux box, etc?

**Comment by gugu** [comment]
@willnorris after you created newer docker image on dockerhub it refreshed trusted roots and problem is not a problem now. Probably you will want to refresh trusted roots each time docker command starts
