### ISSUE TITLE
Add a version tag (other than Latest) to the docker image

### ISSUE THREAD

**Issue by joostlammers** [willnorris/imageproxy#99]
Currently the docker image only has the tag latest.
Whenever a new version becomes available, people using this docker 'latest' image cannot choose whether they want to upgrade or not.
This will become particularly bad whenever there are breaking changes on the interface.

**Comment by willnorris** [comment]
Docker Hub config has been updated to include tagged builds.  Looks like `v0.6.0` kicked off properly but failed to build, so I'll have to dig into it a bit more.  I'm not sure if I can force it to retroactively build older versions, but at least we'll have this going forward once I get it fixed.  Thanks for the suggestion.

**Comment by garthenweb** [comment]
I would love to see this fixed! We were using our own fork but I would like to go back to the original version now, this issue is holding me back somehow because I cannot be sure that our application runs stable in production.
Is there any progress or opportunity to help?

**Comment by willnorris** [comment]
It looks like the "v0.7.0" build succeeded, so I guess this is working now: https://hub.docker.com/r/willnorris/imageproxy/tags/.  I'd love for someone else who is actually using these Docker images (I'm not) to confirm that this is now working as expected before I close the issue.

**Comment by gugu** [comment]
Yes, it does. Thank you.

```
# kostenko @ Andriis-MacBook-Pro-2 in ~/w/shorturl_public on git:master o [19:32:17]
$ docker pull willnorris/imageproxy:v0.7.0
v0.7.0: Pulling from willnorris/imageproxy
fb36d93e3712: Pull complete
0d9fa219e66f: Pull complete
8debf387eaa1: Pull complete
dde823e02eeb: Pull complete
Digest: sha256:f93719f45ce86a3eec1615da5ab9442edac8c36786e790a86cb164370115c13a
Status: Downloaded newer image for willnorris/imageproxy:v0.7.0

# kostenko @ Andriis-MacBook-Pro-2 in ~/w/shorturl_public on git:master o [20:48:25]
$ docker run willnorris/imageproxy:v0.7.0
imageproxy listening on 0.0.0.0:8080
```

**Comment by gugu** [comment]
Deployed to prod, tested. Working

**Comment by LoicMahieu** [comment]
Tested and now deployed! Big thanks @willnorris 👌

**Comment by willnorris** [comment]
Thanks for confirming.
